### ISSUE TITLE
crash with the forge debug profiler

### ISSUE THREAD

**Issue by someaddons** [someaddons/performant_issues#1]
**Describe the bug**
When running the forge debug profiler, loading certain entities causes a crash.

**To Reproduce**
1. run ./debug start
2. Load some chunks/entities (Seems to be zombies/skeletons)

**Expected behavior**
Shouldn't crash.

** Mod version **
performant 3.10m

** Logs **
https://gist.github.com/Alkiasan/7ee6cdde27fcaf6c5c6831b5e897966b

**Comment by DenneyLewis** [comment]
I am also having this issue.

**Comment by someaddons** [comment]
optifine.
