### ISSUE TITLE
crash on server

### ISSUE THREAD

**Issue by justicebearx** [someaddons/performant_issues#10]
It happens every day on server 
But I don't know why

performant-1.15-3.10m
MixinBootstrap 1.0.3
forge-1.15.2-31.2.30

[Crash Report](https://gist.github.com/justicebearx/4664d59728c26eb418c21aff2bd2a10f)

**Comment by someaddons** [comment]
seems vanilla gets stuck trying to load a chunk for some reason

**Comment by justicebearx** [comment]
> 似乎香草由于某种原因而试图装载大块时卡住了

thx I'll get back to you if I have a clue

**Comment by justicebearx** [comment]
It seems to be related to the SereneSeasons-1.15.2
It didn't happen again after I deleted SereneSeasons-1.15.2
default configuration：
36 hours is four seasons，Autumn ends in 24 hours，
It happens when winter comes
This occurs only when both SereneSeasons-1.15.2 and performant are installed simultaneously
