### ISSUE TITLE
Playing on LAN, entities stop or barely move if host is out of chunk

### ISSUE THREAD

**Issue by agr21** [someaddons/performant_issues#101]
game version: 1.16.3 
performant version: latest

Every time if the host goes out of range, entities either barely move or stop altogether. They dont lag, they are still killable but they dont move. also makes villagers lose their profession over time

**Comment by someaddons** [comment]
probably using optifine on the host which got some entity activation radius thingy. Anyways I'm not supporting lan mode, it got too many problems itself. You should just switch to running it as a full server on the hosts machine that works much better with mods
