### ISSUE TITLE
Crash every time I try to remove it

### ISSUE THREAD

**Issue by bryan161** [someaddons/performant_issues#103]
There is a proper way to uninstall? Am I losing something?

**Comment by ravenbuilder934** [comment]
Can you send the crash report, preferably in a pastebin/github gist/etc?

**Comment by bryan161** [comment]
https://gist.github.com/bryan161/7ffd925a4ed979b3c146020e764b98bb

**Comment by bryan161** [comment]
I've never done one so... Did you mean this?

**Comment by ravenbuilder934** [comment]
Yup, thanks
Don't know enough to determine the problem though, someaddons should be here soon to take a look

**Comment by someaddons** [comment]
crash is unrelated to performant, performant just happens to overwrite the part in question, making it not crash. When you remove performant that doesnt happen anymore and the original issue there surfaces. As performant does not persist any data it doesnt affect anything after removing it, so you need to figure out which of the other mods cause that crash. Probably by try n error as the log doesnt seem to show sth useful

**Comment by Jkosio23** [comment]
I was having this while running optifine HD U G5, and updating to G7 fixed it, just for op to have a possible fix
