### ISSUE TITLE
[1.16.5] Passable Foliage does not work properly with fast collisions

### ISSUE THREAD

**Issue by MarioSMB** [someaddons/performant_issues#105]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
The Passable Foliage mod alters the way leaves work, Performant doesn't appear to support it properly, requiring fast collisions to be switched off.

**To Reproduce**

**Expected behavior**
Leaves in the mod are altered to produce a sound and slow your movement, also preventing most fall damage.

**Screenshots**

** Mod version **
3.30m

** Logs **

**Comment by someaddons** [comment]
should be fixed in 3.40m
