### ISSUE TITLE
Mobs have trouble looking at player

### ISSUE THREAD

**Issue by BugmanBugman** [someaddons/performant_issues#108]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
Mobs do not look at the player when and look off to the side

**To Reproduce**
1. With a performant, engage with a hostile and try to get it to chase you
2. Notice how its head can't focus on the player at times and looks off to the side

**Expected behavior**
Mobs usually are able to focus on the player without any problem or distraction

**Screenshots**
![2021-02-16_14 35 01](https://user-images.githubusercontent.com/40730042/108119350-44033200-7065-11eb-8a5e-2c2875044e01.png)

** Mod version **
3.30m

**Comment by dromedar17** [comment]
I have the same issue. (forge-36.0.46 and performant-3.30m)
This is especially noticable with skeletons, which can shoot the player even though they are not looking or aiming in that direction.
They seem to invariably stare of to the left of the player, even while circling around them. Maybe there is a math error somewhere in the computation of the direction the model faces?

**Comment by yangberdo** [comment]
I face this issue as well , hope they can fix this

**Comment by someaddons** [comment]
should be fixed in 3.40m
