### ISSUE TITLE
Player is able to pass through worldborders

### ISSUE THREAD

**Issue by Naxdar** [someaddons/performant_issues#109]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
Performant on the client allows the player to pass through worldborders (in singleplayer and on dedicated servers). Without Performant on the client, the player is correctly stopped by the worldborder.
Tested on Forge 36.0.42 with Performant 1.16.2-4-3.30m alone, on a dedicated forge server with no mods.

**To Reproduce**
Start a singleplayer world, or connect to a dedicated server
Set the worldborder to a distance close to you
Go through the worldborder

**Expected behavior**
The player is blocked by the world border.

**Screenshots**
Not really needed.

** Mod version **
Performant 1.16.2-4-3.30m

** Logs **
No crash

**Comment by someaddons** [comment]
should be fixed in 3.40m
