### ISSUE TITLE
[1.16.1] Extra character in chat with performant command returns

### ISSUE THREAD

**Issue by jinkhya** [someaddons/performant_issues#11]
**Describe the bug**
All the commands return some text starting with Â

**To Reproduce**
Run any performant command either on client or server.

**Expected behavior**
I'm guessing this is not intended and that "Â" shouldn't be there :)

**Screenshots**
https://imgur.com/a/VUAwgRK

** Mod version **
3.11m

**Comment by someaddons** [comment]
oh ye vanilla sometimes does this for color-formatted text, I gotta switch to the newer formatting in a few places still which doesnt have that issue

**Comment by someaddons** [comment]
fixed
