### ISSUE TITLE
Spam in console

### ISSUE THREAD

**Issue by mihionmc** [someaddons/performant_issues#112]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**

After setting the mod up on my direwolf20 1.6.1 "1.16.4" i experienced that the console was spamming this:
https://pastebin.com/aA5BnqPS
It stoppede after I removed the mod.
 
**To Reproduce**

**Expected behavior**

**Screenshots**

** Mod version **
Your mods version

** Logs **
Latest/Crash log

**Comment by someaddons** [comment]
its environmental tech spamming the log
