### ISSUE TITLE
Conflict with Neapolitan mod

### ISSUE THREAD

**Issue by rafaelkai** [someaddons/performant_issues#115]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
When loading Performant with Neapolitan the game crashes at startup.

**To Reproduce**
1. Use Performant and Neapolitan
2. Load the game

**Expected behavior**
Not to crash.

**Mod version**
Performant 1.16.2 (Lastest)
Neapolitan 2.1.0 (Lastest)

**Logs**
[latest.log](https://github.com/someaddons/performant_issues/files/6089873/latest.log)

**Comment by someaddons** [comment]
should be fixed in 3.40m
