### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jklw10** [someaddons/performant_issues#117]
https://bugs.mojang.com/browse/MC-158597

clientside still does entity collision checks when the team rule for it is off. i would like this fixed. also performance increases on entity collision overall would be appreciated.
this is from a world with 2.4k sheep on it all on a team with team collision rule NEVER.

https://spark.lucko.me/Dbh4py6gqZ

**Comment by jklw10** [comment]
taking a look on fabric side. it seems the accurate function would be entity cramming. and yes even with max entity cramming at 0 the lag is still there

**Comment by someaddons** [comment]
should be fixed in 3.40m
