### ISSUE TITLE
[Suggestion] Provide an API for mod developers

### ISSUE THREAD

**Issue by MarioSMB** [someaddons/performant_issues#126]
To preface this, I'd just like to state that I do understand wanting to keep the mod's source code private, and while it is misguided, that is not the topic of this issue.

Currently, Performant has a bit of a reputation among mod developers as that addition players use that makes debugging infuriating (indeed, in many cases when the issue cause is tracked down to Performant in other mods' trackers, it will simply be closed), not unlike OptiFine. Mod compatibility issues need to be addressed directly by the Performant developer(s), making it a nightmare for all involved parties.

---------------
In the early days of Minecraft modding, users would have to place mod contents directly into the .jar file. This was of course not flexible in the slightest, getting even a handful of mods to even load was an extremely tedious process.  
Then along came mod APIs such as Forge (and later Fabric), which provided mod developers with the hooks needed to create their mods without getting involved directly with the Minecraft code. This has led to the amazing modding scene we have currently, where the game is being extended in so many ways by many different developers, all thanks to the flexibility of APIs.

Now onto Performant and the core of this suggestion: like Forge, it would be worthwhile to create an API or extensive documentation for how your mod works, so that mod developers can hook into it and allow their mod to be compatible with Performant.  
This would reduce the amount of work needed on your part to keep individual mods functional, as well as reducing the size and impact of the Performant mod on its own, without needing the full code to be open sourced.

Thank you for your time, I hope something like this can be considered as it would greatly improve the mod's reputation and overall support.

**Comment by BugmanBugman** [comment]
I agree, please look into this. Would help everyone all around

**Comment by Corvus20** [comment]
I second this idea. Optifine and Performant get a lot of flak from others for the lack of this sort of thing. Providing documentation would not only allow for better compatibility with other mods, but other developers hooking into your mod can provide valuable insight on how to improve it, things that you otherwise might have overlooked. It's always good to have something looked at from multiple perspectives.

**Comment by someaddons** [comment]
I'll look into it, however most systems are described on the page/configs already and should interact just like vanilla
