### ISSUE TITLE
Breaks Botania Heisei Dream Flower

### ISSUE THREAD

**Issue by JaredNeil** [someaddons/performant_issues#127]
### Describe the bug
Performant breaks Botania's Heisei Dream flower that causes mobs to attack each other.
After spawning a lot of zombies, I saw a few bugs:
1. The zombies don't all attack each other like they do without performant enabled
2. One time all of the zombies attacked one of the other zombies, then went back to idle after it died.
3. A few times one of the zombies would attack and kill itself.

### To Reproduce
1. Load world with Botania (and dependencies Patchouli and curios-forge) and performant
2. Place Heisei Dream and creative mana pool
3. Spawn two zombies
4. Notice they don't attack each other

### Expected behavior
Heisei dream flower causes zombies to attack each other.

### Mod versions
Botania-1.16.4-414
curios-forge-1.16.5-4.0.5.0
Patchouli-1.16.4-50
performant-1.16.2-5-3.40m

**Comment by someaddons** [comment]
should be fixed in 3.57
