### ISSUE TITLE
swim selector bug

### ISSUE THREAD

**Issue by mahjerion** [someaddons/performant_issues#13]
**Describe the bug**
Not really sure how it started as I host the official Craft to Exile [Dissonance] server, but I have crash logs that may be of use to you. Once it began, server would crash upon player log in. Note: this happens on 3.11m and when I went back to 3.10m it seemed to be okay.

**To Reproduce**
1. Log into server.
2. Crash!

**Expected behavior**
No crash.

**Screenshots**
N/A

** Mod version **
Performant 3.11m

** Logs **
Latest/Crash log
https://gist.github.com/mahjerion/6f478a21a147100c8634bf9cdb94f79d

**Comment by MidnightsFX** [comment]
I have also very rarely seen these, almost exclusively when idling (after world creation etc).

For me they are almost always Salmon, which is probably explained by the fact that I am not normally around the ocean.

Hopefully the additional datapoints help, [crashlog](https://gist.github.com/MidnightsFX/e702dd296573b7c3873ed6a8cc7b64b8).

**Comment by nmills3** [comment]
Same happened on my server when a player was building near an ocean

**Comment by ghostbear77** [comment]
I'm playing the Valhelsia 2 Modpack in singleplayer, the game crashes often (several times a day) with the same error. The entity is different most of the time. Disabling ["Entity settings"]->fastPathFinding did not help, just turned the NPE into an ArrayOutOfBoundsException.

[Crash report on PasteBin](https://pastebin.com/kidza41Q)

**Comment by someaddons** [comment]
should be fixed in v3.12m

**Comment by MidnightsFX** [comment]
Awesome! will 3.12m be available for 1.15?

**Comment by MidnightsFX** [comment]
> Awesome! will 3.12m be available for 1.15?

Seeing it on curse now. Excited to test it out, great work on this!
