### ISSUE TITLE
Minecraft crashes when using chunk pregenerator mod

### ISSUE THREAD

**Issue by XxZajoZzO** [someaddons/performant_issues#130]
**Describe the bug. 1.12 is no longer supported, do not make bug reports for it.**
If you have performant installed and use chunk pregenerator to pregenerate the world minecraft will crash

**To Reproduce**
1. Click on new world
2. Click preview world
3. Click start
4. Wait
5. Minecraft will crash

**Expected behavior**
Minecraft does not crash

** Mod version **
MC 1.16.5
performant-1.16.2-5-3.40m
forge 36.1.4
java 1.8.0-281
Chunk Pregenerator-V1.16-3.0.5

** Logs **
https://mclo.gs/jYljvhx
https://mclo.gs/7kIRtuS
https://pastebin.com/SiTd66PW
https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator/issues/124

**Comment by Speiger** [comment]
I am not sure what you are changing to cause this crash. Because this logic does happen only in 3.4m while 3.3m works fine.
But i want to resolve this so this does not happen anymore.

**Comment by someaddons** [comment]
should be fixed

**Comment by Speiger** [comment]
Thank you for the quick response and action.
