### ISSUE TITLE
[1.16.5] Incompatibility with Environmental's Kiln

### ISSUE THREAD

**Issue by MarioSMB** [someaddons/performant_issues#131]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
The kiln from the Environmental mod is not working properly; items cooked in it are taking the same amount of time as a regular furnace. See here: https://github.com/team-abnormals/environmental/issues/186

**To Reproduce**
1. Cook any item in the Kiln station from the Environmental mod
2. It will take 10 seconds instead of 5

**Expected behavior**
It is expected to be able to configure the cooking time of custom stations

**Screenshots**

** Mod version **
3.40m

** Logs **

**Comment by MarioSMB** [comment]
It looks like the Kiln is actually being treated as a furnace... items that can only be smelted and not baked are being incorrectly processed by the Kiln.

**Comment by someaddons** [comment]
should be fixed

**Comment by MarioSMB** [comment]
I've just tested again with 3.54m, this does not appear to be fixed.
