### ISSUE TITLE
[1.16.5] Crash with tasmanian devil from alex's mobs

### ISSUE THREAD

**Issue by frank89722** [someaddons/performant_issues#132]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**

**To Reproduce**
1. Install Alex's mobs and spawn a Tasmanian devil
2. Crash

**Expected behavior**
When fastCollisions and multiEntities set to true the game will crash.

**Mod version**
performant-1.16.2-5-3.40m.jar
alexsmobs-1.9.0

**Logs**
https://gist.github.com/frank89722/26433856289911171340f1919d20f126

**Comment by someaddons** [comment]
should be fixed
