### ISSUE TITLE
[1.16.5] Neapolitan agility buff broken

### ISSUE THREAD

**Issue by MarioSMB** [someaddons/performant_issues#133]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
The agility buff from eating Neapolitan's bananas is supposed to provide the ability to climb any block. This is currently broken by Performant's fast collisions.

** Mod version **
3.40m

**Comment by someaddons** [comment]
fixed in newest

**Comment by curryducker** [comment]
bug appears to be still there/back in version 3.95m
