### ISSUE TITLE
Incompatibility with Spider 2.0

### ISSUE THREAD

**Issue by gglobensky** [someaddons/performant_issues#134]
FML 35.1.36
Minecraft 1.16.4

Spiders get stuck on walls using performant and Spider 2.0 mod

using these settings allows them to act normally

fastCollisions = false
fastPathFinding = false
multiEntities = false

Ref: https://github.com/TheCyberBrick/Spiders-2.0/issues/37

I was wondering if there would be a way to omit only the spiders from the fastCollisions and fastPathFinding as a way to add a compatibility mode with this mod.

**Comment by someaddons** [comment]
https://github.com/someaddons/performant_issues/issues/53 duplicate
