### ISSUE TITLE
1.16.5 How disabled this message?

### ISSUE THREAD

**Issue by Senyum** [someaddons/performant_issues#136]
Hi, what option in config disabled this message? Link in message not found

**Screenshots**
![Screenshot_3](https://user-images.githubusercontent.com/36424845/115504421-97ba1380-a280-11eb-8ba1-5f2d47598510.png)

** Mod version **
Performant-1.16.2-5-3.53m

**Comment by someaddons** [comment]
its a resourceful bee's nonesense, ask them
