### ISSUE TITLE
Performant breaks Environmental's nest block's functionality

### ISSUE THREAD

**Issue by vilewrath** [someaddons/performant_issues#137]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
Fast hopper setting breaks Environmental's nest functionality

**To Reproduce**
1. Get Abnormal's Environmental
2. Make sure fasterHoppers is set to true
3. Place a nest on top of a hopper and fill with eggs (right-click with egg)

**Expected behavior**
The eggs _should_ have left the nest and entered the hopper

[Here is the source code for the nest tile](https://github.com/team-abnormals/environmental/blob/1e2a72c98a18fcce56a56084c37c64860a3ef8ba/src/main/java/com/minecraftabnormals/environmental/common/tile/BirdNestTileEntity.java)

**Comment by someaddons** [comment]
fixed
