### ISSUE TITLE
Performant 3.53m crash on join a world

### ISSUE THREAD

**Issue by frank89722** [someaddons/performant_issues#138]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**

**To Reproduce**
1. Join a world in single player

**Mod version**
Forge 36.1.4
Performant 3.53m

**Logs**
https://gist.github.com/frank89722/e0e885a3933d05b186c941db2d3890a5

**Config**
https://gist.github.com/frank89722/5aed610e79aae5f957d9373a2179d96c

**Comment by someaddons** [comment]
fixed
