### ISSUE TITLE
[1.16.5] Dedicated server hard lock - com.performant.coremod.entity.ai.CustomGoalSelector.onUpdateTasks()100.00% 289700ms

### ISSUE THREAD

**Issue by ProsperCraft** [someaddons/performant_issues#139]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**

**To Reproduce**
No idea

**Screenshots**
Warmroast of the server while 100% locked up for over 10 minutes.
![Performant](https://user-images.githubusercontent.com/4427684/115896755-fb774480-a418-11eb-9fad-243afe5feb2f.png)

** Mod version **
performant-1.16.2-5-3.40m
I am removing AI-improvements, and updating to performant-1.16.2-5-3.54m
 to see if it happens again.

** Logs **
Debug log - https://gist.githubusercontent.com/ProsperCraft/4c441cd7d292a9da830df4c29cf394b3/raw/24c7f17f446d8133cac01f1e01d27754f95fefbc/gistfile1.txt

**Comment by someaddons** [comment]
ye updating should probably fix it
