### ISSUE TITLE
Client crash on boot [1.12.2]

### ISSUE THREAD

**Issue by YOYOK9** [someaddons/performant_issues#14]
**Describe the bug**
Just wanted to bring this to your attention if it hasn't been already. Seems the mod crashes on client side boot. With mixins removed it still crashes unfortunately. Be really nice to use this mod as 1.15+ is still relatively new and not all the mods in my public modpack have been updated yet. 

Mixin issue: https://github.com/LXGaming/MixinBootstrap/issues/34
**To Reproduce**
1: create a pack with just MixinBootstrap and performant (1.12.2)
2: Start pack

**Expected behavior**
For it to boot successfully 

**Screenshots**
Proof of just the 2 mods loaded:
https://puu.sh/GqGMU/99de32bdf9.png

Crash shown from twitch client:
https://puu.sh/GqH21/69e2b1484f.png

** Mod version **
MC: 1.12.2
Forge: 14.23.5.2854
Mixin: 1.0.3
Performant: 1.12.2-1.10

** Logs **
No crash report given. Just the Latest Log. 
Boot launcher Log: https://pastebin.com/eHibZ4xi
Latest log: https://pastebin.com/L3KjKtHs

**Comment by someaddons** [comment]
1.12 is old and no longer supported
