### ISSUE TITLE
Ticking Entity Crashes

### ISSUE THREAD

**Issue by thelapisfox** [someaddons/performant_issues#140]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
Game randomly crashes. This could happen a few minutes to a few hours into gameplay. Also, see https://github.com/noeppi-noeppi/MythicBotany/issues/41 & https://github.com/owmii/Powah/issues/176

**To Reproduce**
1. Play game for a bit
2. Crash
3. See error

**Expected behavior**
Game plays without constantly crashing

** Mod version **
MC: 1.16.5
Forge: 36.1.4
Performant: 1.16.2-5-3.40
Modpack: Direwolf20 1.16 Version 1.9.0 (with a couple of extra mods)

** Logs **
Latest/Crash log
https://paste.ee/p/9CwDG
https://paste.ee/p/JDro4
https://paste.ee/p/N8pvC
https://paste.ee/p/XyD0r
https://paste.ee/p/tXuJv
https://paste.ee/p/1ZflU

EDIT: Thought I should mention that I am playing this on a dedicated server. The server doesn't crash, only the client. Currently playing it with this mod disabled on client. Will return to update this with a status.

UPDATE 5/8/21: No more TBE crashes since disabling this mod on client side.

**Comment by someaddons** [comment]
update to the newest, you're quite outdated

**Comment by someaddons** [comment]
should be fixed in 3.57
