### ISSUE TITLE
Server console errors with JAOPCA

### ISSUE THREAD

**Issue by cpm9** [someaddons/performant_issues#141]
**Description**
_A lot_ of errors appear in server console when using Performant with JAOPCA,. If this is not a Performant issue I apologize and in that case I will make this bug report on JAOPCA's github

**To Reproduce**
1. Start forge server with Performant mod and JAOPCA mod
2. 1400 lines of console errors mentioning performant and jaopca appear in console while server is starting

**Expected behavior**
Not 1400 lines of errors in server console during startup.

**Screenshots**

** Mod version **
Forge 36.1.16
Performant-1.16.2-5-3.55m
JAOPCA-1.16.5-3.4.0.8

** Logs **
[https://pastebin.com/Y2KbQ8B9](https://pastebin.com/Y2KbQ8B9)

**Comment by someaddons** [comment]
ye thats an intended warning for when mods add a loottable without name

**Comment by MrNinja93** [comment]
Either I'm blind or such an option doesn't exist, would it be possible to add a config option to disable the loot table null name console logging?
