### ISSUE TITLE
Incompatibility with Pehkui Mod

### ISSUE THREAD

**Issue by congueror** [someaddons/performant_issues#142]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
When both performant and pehkui is installed minecraft crashes. Log can be found below. Not sure if this is a problem with pehkui or you so I've reported the problem to both.

**To Reproduce**
1. Download Performant
2. Download Pehkui
3. Launch Game
4. Witness disappointment

**Expected behavior**
Reach the title screen.

**Screenshots**
Irrelevant.

** Mod version **
MC Version: 1.16.5
Forge Version: 36.1.16
Performant: 1.16.2-3.55m
Pehkui: 1.16.5-2.0.0 (forge of course)

** Logs **
https://pastebin.com/hHc10ETP

**Comment by congueror** [comment]
Oh I didn't see it, thanks.

**Comment by Kqmu** [comment]
Would be helpful if this issue got fixed
