### ISSUE TITLE
Performant incompatible with create.

### ISSUE THREAD

**Issue by StormCircuit** [someaddons/performant_issues#143]
Use performant out of the box. Use create out of the box. Create's machines and tile entities do not update with performant's tile entity multi-threading enabled. Easy example is the Create Fluid Valve with a valve handle. Place the valve handle on the valve to open/close it and proceed to rotate the valve to initiate the open/close action. Valve shows as having rotated enough but does not change from closed to open (vice versa).

**Expected behavior**
Create's tile entities to update properly.

**Screenshots**
I can attach some if necessary, it felt fairly self explanatory.

** Mod version **
create-mc1.16.5_v0.3.1c.
performant-1.16.2-5-3.54m

** Logs **
Nothing in logs seems like it would help. Let me know and I can attach them.

**Comment by someaddons** [comment]
should be fixed in 3.57
