### ISSUE TITLE
JourneyMap Crashes the game

### ISSUE THREAD

**Issue by Peca21** [someaddons/performant_issues#144]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
When selecting auto-map in JourneyMap, game crashes.

**To Reproduce**
1. Open JourneyMap
2. Select Auto-Map
3. Crash

**Expected behavior**
No Crash

** Mod version **
performant-1.16.2-5-3.55m

** Logs **
https://pastebin.com/NjLVQ3CD
https://pastebin.com/2sN13BAK

**Comment by someaddons** [comment]
should be fixed in the newest
