### ISSUE TITLE
SSP & SMP crash

### ISSUE THREAD

**Issue by Lurmey** [someaddons/performant_issues#145]
Game crash seemingly randomly. Has occurred three times, first on the death of a horse, second on damaging a creeper, third while flying with Elytra. Unsure if caused by Performant, but the crash log mentions Performant as well as Optifine and Dynamic Trees. Incompatibility?

** Mod version **
Performant 1.16.2-5-3.55m | Forge 36.1.10

** Logs **
Latest/Crash log
[crash-2021-05-08_19.02.19-server.txt](https://github.com/someaddons/performant_issues/files/6446319/crash-2021-05-08_19.02.19-server.txt)

**Comment by someaddons** [comment]
should be fixed in the newest
