### ISSUE TITLE
Mismatched push/pop calls in debug profiler

### ISSUE THREAD

**Issue by ItsTristan** [someaddons/performant_issues#146]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
Performant seems to generate mismatched push/pop calls in the Minecraft debug profiler. This appears as repeatedly nested "tick" events in the results, and an error message about the remaining path "tick.tick.tick.tick...." in the logs.

**To Reproduce**
1. Run the command `/debug start`
2. Issue appears in the log and in the generated debug profile.

**Expected behavior**
`tick` path should not be repeatedly nested.

**Mod version**
performant-1.16.2-5-3.55m
forge-36.1.10

**Logs**
https://gist.github.com/ItsTristan/d7bd7347c1d031fc25925e22b2749b3b

**Comment by azimut3** [comment]
This affects me either

**Comment by Swedz** [comment]
I was having this same issue too when trying to run the debug profiler to try and find the source of lag. I ended up installing [Spark](https://www.curseforge.com/minecraft/mc-mods/spark) (which, I didn't know had a forge version, thought it was for spigot & paper only!) and the results weren't making any sense. Not sure if you're having lag issues you're trying to resolve, but uninstalling performant from my server solved the lag for me.
