### ISSUE TITLE
Improved Mobs block breaking and guardian ride time

### ISSUE THREAD

**Issue by Rx2TF** [someaddons/performant_issues#148]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
Having performant installed breaks Improved Mobs block breaking behavior and introduces a delay for mobs to ride guardians on water.

**To Reproduce**

For block breaking:
1. Encase villager in Improved Mob's ai Block break whitelist (eg. Glass Blocks)
2. Spawn zombies to get a block breaking zombie (holds an enchanted diamond pickaxe by default)
3. Observe no block breaking

The guardian ride delay is noticeable as aggro'd mobs in water sink / stay in water a fair distance before riding guardians.

**Expected behavior**
Block breaking and faster guardian riding.

** Mod version **
TenshiLib 1.3.0
Improved Mobs 1.7.6
Performant 3.56m

**Comment by BugmanBugman** [comment]
Am experiencing this as well

**Comment by someaddons** [comment]
will be fixed in the next improved mobs version
