### ISSUE TITLE
Crash with new update

### ISSUE THREAD

**Issue by aAndrew3030** [someaddons/performant_issues#152]
After updating to the latest version, it is crashing at random.

[crash-2021-05-24_10.42.42-client.txt](https://github.com/someaddons/performant_issues/files/6533198/crash-2021-05-24_10.42.42-client.txt)

**Comment by aAndrew3030** [comment]
3.57 and 3.58 both crash. I have no issues with 3.56

**Comment by someaddons** [comment]
fixed in 3.59, but its probably a mekanism error, seems they fire the event without a sound manager
