### ISSUE TITLE
[Bug] Dragons from ice and fire, and some mobs from alex mobs stutter in place and don't move until you are very very near them

### ISSUE THREAD

**Issue by winsrp** [someaddons/performant_issues#153]
**To Reproduce**
Install either alex mobs or Fire and Ice
Mobs such as the elephant in the sabana, and flying dragons stutter in place.

If yo have a flying dragon it will stay in the air and move at like 1 frame every 10 secs?, same with the other mobs, such as cyclops, crocodiles, and so on... 

** Mod version **
performant-1.16.2-5-3.59m
alexsmobs-1.10.1
iceandfire-2.1.6-1.16.4

**Comment by winsrp** [comment]
Add flying flame arrows, that you shoot into the sky.. they get stuck in the sky.. .and enemies that stutter bounce arrows back.. very weird. XD

**Comment by someaddons** [comment]
ye the new one has an entity activation range added,  can turn `enableDynamicEntityUpdates` off in the config to disable it. Going to look into it though, normally it shouldnt happen that close at all

**Comment by someaddons** [comment]
try v3.60m

**Comment by winsrp** [comment]
will give it a try later today and let you know tx

**Comment by winsrp** [comment]
played a bit and look a lot better, if I see something else come up I'll post it here. tx

**Comment by someaddons** [comment]
nice, always good to get some feedback :)
