### ISSUE TITLE
Skeleton bug

### ISSUE THREAD

**Issue by aAndrew3030** [someaddons/performant_issues#154]
Using the latest version 3.60m I had lightning strikes spawning skeleton horses, by the thousands! It quickly lagged out and froze the game. It did not crash (just froze up) so no crash report, but I assume it has to do with the fix that was made for skeletons
![Screenshot 2021-05-26 002520](https://user-images.githubusercontent.com/84727133/119602626-87ceab80-bdb9-11eb-8678-d393528dae7b.jpg)

**Comment by someaddons** [comment]
fixed in 3.61
