### ISSUE TITLE
Hostile entities despawn issue with noLagItemPickup 

### ISSUE THREAD

**Issue by frank89722** [someaddons/performant_issues#155]
**To Reproduce**
1. Set noLagItemPickup to true.
2. Fly up 32 blocks above the nature spawn hostile entities.
3. All hostile despawn instantly.

**Expected behavior**
Minecraft usually despawns mobs after 2 minutes, disable noLagItemPickup can see the difference.
But I'm not sure this is a feature or a bug.

**Mod version**
performant-1.16.2-5-3.61m
forge 36.1.16

**Comment by someaddons** [comment]
noLagItemPickup just has them search for items a bit less often, it has no effect on despawns. Might've been just rng? despawning varies a bit with randomness

**Comment by frank89722** [comment]
I know it's quite strange but I have tested it over three times with only performant installed and the result is the same.

Here are some GIFs (file is too large so I uploaded to GD): https://drive.google.com/drive/folders/1jXtc9Av69daXPhUcOZ2WjKycz7Wlt9Me?usp=sharing

**Comment by someaddons** [comment]
ah found it, I did adjust the spawning radius a little to get better mob spawning and that setting happens to turn it off. I guess thats more of a feature then xD

**Comment by frank89722** [comment]
If you could move it to a new setting it would be great.
I'm currently playing with a mod that adds some effect to vanilla mobs. So I usually use a jetpack to kill them in the air, but sometimes I will fly too high by accident and they will disappear :(

**Comment by someaddons** [comment]
well killing them from the air is pretty much cheating the system anyways :D but ye I wanted to improve upon it in the future, can just use the config to turn it off for now

**Comment by someaddons** [comment]
fixed in 3.66
