### ISSUE TITLE
Hostile mob spawn radius is broken and not configurable

### ISSUE THREAD

**Issue by LeftofZen** [someaddons/performant_issues#158]
Hostile mobs such as hoglins do not spawn in the normal spawn radius. Many farms such as this: https://www.youtube.com/watch?v=GlgCZbHSk6c&ab_channel=Shulkercraft do not work with this mod. The reason this is an issue is because there is no configuration option to reset the spawn radius for mobs back to the original minecraft value.
I can guarantee that Performant is at fault because I tried before/after scenarios with disabling the mod. I have tried disabling the config option `fastSpawnRadius` to no avail.

1. Add Performant mod.
2. Make a hoglin farm as in the video linked.
3. Notice that even at 127 vertical blocks away, no hoglins spawn.
4. Disable Performant, and see the farm working as intended.

**Expected behaviour**
Mob spawn range is identical to vanilla behaviour, and/or a config option is provided to configure the range.

**Screenshots**
N/A, its just gonna be me being 127 blocks away from the platform and showing no hoglins with Performant enabled, and many hoglins spawning without Performant enabled.

**Mod version**
MC 1.16.5
Forge 36.1.24
performant-1.16.2-5-3.64m.jar

**Logs**
Game doesn't crash, its just the mod doesn't work

**Comment by LeftofZen** [comment]
I also jsut want to mention that I have seen this similar issue
https://github.com/someaddons/performant_issues/issues/155

and whilst the symptoms and description are identical, I have also tried disabling `noLagItemPickup` and still have the mobs despawn immediately after 32 blocks with no respawn ever.

**Comment by someaddons** [comment]
fixed in 3.66

**Comment by LeftofZen** [comment]
Amazing, thankyou very much <3

**Comment by YousifKH115** [comment]
i know this is an old post but i am experiencing the same problem but the distance is different, hoglins despawn after 60 blocks when i'm way. I don't have the same mod installed though.

Minecraft 1.21.1
modpack "essential mods" v30.0.0
NeoForge
