### ISSUE TITLE
Performant 1.15-3.11m hard crashes with Lithium

### ISSUE THREAD

**Issue by FSwordFoxA** [someaddons/performant_issues#16]
**Describe the bug**
Performant 1.15-3.11m and Lithium 0.4.6-rc3 don't work together. At all. Any world I try to join or create results in a hard crash with the following error: "exception initializing level". But if I roll Performant back to version 2.02m, I become able to make/join worlds again.

The Forge version of Lithium is no longer being supported by its author, they only support Fabric versions of their mods now. It may be finally time to stop using the Forge version of Lithium, though can some of what it does be added to Performant if Performant doesn't already do it?

**To Reproduce**
1) Install Performant and Lithium.
2) Start Minecraft and try to make a new world.
3) Minecraft starts generating a world then crashes to desktop.
3.1) The world is still technically "created", as it is in the world list, but it crashed before you joined it.
4) See error report in the console.
5) Roll back Performant to 2.02m
6) Start Minecraft again.
7) Make another new world.
8) Successfully join world.

**Expected behavior**
Being able to join and create worlds even with just Performant 3.11m, Lithium 0.4.6-rc3, and their required dependencies loaded.

** Mod version **
Forge: 31.2.37 (Also affects 31.2.36)
Performant: 1.15-3.11m
Lithium: 0.4.6-RC3

** Logs **
https://gist.github.com/FSwordFoxA/354f3817c272234d52ad6a83ff92a24a#file-gistfile1-txt

**Comment by someaddons** [comment]
Lithium no longer gets updates for forge, and performant covers what it does anyways so I see no reason to spent time on compat
