### ISSUE TITLE
unable to craft anything with Artisan Worktables

### ISSUE THREAD

**Issue by OrangeBurrito** [someaddons/performant_issues#160]
When I join the game with Performant and Artisan Worktables  a warning message says that Artisan Worktables is incompatible with Performant, and I am unable to craft anything with the worktables.

Steps to Reproduce:
1. Launch the game with Artisan Worktables, Anathaeum (the library mod), and Performant.
2. A message appears in game saying Artisan Worktables is incompatible with Performant.
3. The player is unable to craft anything with the worktables.

This issue is listed in the documentation for this mod [here](https://artisan-worktables-116.readthedocs.io/en/latest/knownissues/).

** Mod version **
performant-1.16.2-5-3.66m
artisanworktables-2.0.1
athenaeum-2.0.0

**Comment by someaddons** [comment]
add some example recipes for it and I'll look into it

**Comment by OrangeBurrito** [comment]
I tested recipes for sticks, pumpkin pie and a pie from Harvestcraft 2, and none were craftable with the Worktables/Workstations.

**Comment by someaddons** [comment]
afaik you need to define all the recipes that can be crafted on those special work tables beforehand, try if it even works your way witohut performant

**Comment by OrangeBurrito** [comment]
Apparently I'm stupid because I can't seem to get this worktable to work without the mod either, I'm just removing it. Something about crafttweaker but that's way over budget.

**Comment by someaddons** [comment]
ye I think you have to manually add recipes to the mod else it just has none. Anyways I'll close this then, since that doesnt seem to be a bug :)

**Comment by Freebi85** [comment]
Artisan Tables works correctly on its own but when crafting stuff in those tables while performant is installed  (custom recipes with craffttweaker obviously) stuff gets duped or doesent check correctly for tools and its durability and other stuff like that. 

I use the mod with lots of custom recipes and such and would like to use performant as well.

I haven't tried with disabling caching recipes tho.

**Comment by KubiRemPL** [comment]
> Artisan Tables works correctly on its own but when crafting stuff in those tables while performant is installed (custom recipes with craffttweaker obviously) stuff gets duped or doesent check correctly for tools and its durability and other stuff like that.
> 
> I use the mod with lots of custom recipes and such and would like to use performant as well.
> 
> I haven't tried with disabling caching recipes tho.

Sadly disable caching doesn't solve the problem
