### ISSUE TITLE
When is 1.17 coming out?

### ISSUE THREAD

**Issue by Spiderfffun** [someaddons/performant_issues#164]
The mod seems great, but every time a new version comes out i dont feel like waiting so long for every mod to update, So when will it be out?

**Comment by someaddons** [comment]
when forged updated(it hasnt yet) I'll port it over, which due to mojang changes can take quite a while then fix most bugs and then release it. So its an unknown amount of work required + modding is only a freetime activity thus its literally impossible to give any proper ETA
