### ISSUE TITLE
entity.threading. TickTrackedEntitiesAction

### ISSUE THREAD

**Issue by OcrSu** [someaddons/performant_issues#165]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
entity.threading. TickTrackedEntitiesAction

**To Reproduce**
I appeared in the dimension of hell, and there was no phenomenon when I appeared. This is the error report that I learned from the backstage

**Expected behavior**
There will be no error report in the background

**Screenshots**
https://ftp.bmp.ovh/imgs/2021/07/7cd90a244459031b.png

** Mod version **
3.66m

** Logs **
http://91io.cn/s/ddYoBuM

**Comment by someaddons** [comment]
fixed in newest
