### ISSUE TITLE
Pathfinding crash with AlexMobs

### ISSUE THREAD

**Issue by DreiPixel** [someaddons/performant_issues#166]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
Server is crashing with a Grizzly bear just existing. crash says its related to pathfinding. after i removed performant the issues was gone.

**To Reproduce**
1. have a grizzly bear???

**Expected behavior**
having a grizzly bear and not crashing?

** Mod version **
3.66m

** Logs **
https://gist.github.com/DreiPixel/72a7e16f18a97179fda125c0df075e1a Crashlog

**Comment by someaddons** [comment]
might be fixed with 3.71m

**Comment by DreiPixel** [comment]
> might be fixed with 3.71m

nope. its is still crashing. exact same crash.
 https://gist.github.com/DreiPixel/6fe478f9481f6e2a0fa41db880f138bf
