### ISSUE TITLE
Dragon Mounts 2 Compatibility Issue 

### ISSUE THREAD

**Issue by LegendaryCrystalFox** [someaddons/performant_issues#168]
With this mod and dragon mounts 2 only, the dragons become unfunctional. They do not move, follow, sit, or anything. And once I remove performant, dragon mounts works fine.

Performant Verison: 1.10
Dragon Mounts 2 Verison: 1.6.3
Forge Verison: 1.12.2-14.23.5.2855

**Comment by someaddons** [comment]
1.12 is not supported
