### ISSUE TITLE
Chunks don't save [1.16.5]

### ISSUE THREAD

**Issue by XionioXMaster** [someaddons/performant_issues#171]
**To Reproduce**
1. Go to Enter the game and teleport to 9000 90 9000, put chests or break something
2. teleport back 0 90 0
3. Fly forward a couple of chunks and back again 9000 90 9000
4. You will see that the territory is regenerated back

**Expected behavior**

**Screenshots**
**Nope**

** Mod version **
performant-1.16.2-5-3.71m.jar

** Logs **
**Nope**

**Comment by XionioXMaster** [comment]
3.66m Doesn't have this bug

**Comment by someaddons** [comment]
not reproducible for me in the current version, and please add the logs they are important

**Comment by XionioXMaster** [comment]
https://github.com/MinecraftMist/Mist/issues/9

**Comment by someaddons** [comment]
so some weird alterated fork of forge has the issue? I only support actual forge
