### ISSUE TITLE
[1.16.5] Mining blocks really fast causes audio to cut out a little. (not playing properly, examples in desc.)

### ISSUE THREAD

**Issue by Gbergz** [someaddons/performant_issues#172]
**Describe the bug**
Mining blocks really  fast causes audio to cut out. (not playing continuously. small noticables cutouts.)

**To Reproduce**
1. Install Performant.
2. Go into a world.
3. Grab a shovel, enchant it with Efficiency V.
4. Mine blocks fast.
5. Audio cuts out sometimes.
6. Profit.

**Expected behavior**
That audio plays like normal and no audio cuts like without Performant.

### Videos

**1. (With Performant. Not working correctly, audio cutting out a little, it's noticable.)**
https://streamable.com/e1ffqc

**2. (Without Performant, audio working like normal. no small cut outs. break sound plays continuously.)**
**You can hear the difference between the two examples.**
https://streamable.com/wa9n5y

**Mod version**
[performant-1.16.2-5-3.71m.jar](https://www.curseforge.com/minecraft/mc-mods/performant/files/3389539)

**Comment by someaddons** [comment]
it is an intended mechanic, performant skips playing more than 10 of the same sounds at the same time to reduce unnecessary sound lag

**Comment by Gbergz** [comment]
Ah gotcha. 
Could a config option be added to disable and or choose how many sounds can be played at once?

**Comment by someaddons** [comment]
ye can add that

**Comment by someaddons** [comment]
added in 72
