### ISSUE TITLE
Hang on server stop

### ISSUE THREAD

**Issue by SonarBeserk** [someaddons/performant_issues#174]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
When stopping a server running v5-3.70m the server fails to stop when told to stop. It will show stopping messages but never appears to stop. Testing v5-3.66-v5-3.69 show no issues related to shutdown, it appears some changes in v5-3.70 triggered the issue.

**To Reproduce**
1. Install v5-3.70m+ in mods folder
2. Start Server
3. Stop Server
4. Server continues to run

**Expected behavior**
The server to stop when the server finishes processing the shutdown.

**Screenshots**

**Mod version**
v5-3.70m/v5-3.71m

**Logs**
Latest/Crash log
https://gist.github.com/SonarBeserk/6b065b7cf08cf5de47baf48ac4e8cb81

**Comment by Jordan231111** [comment]
Similar issue here when stopping the server it saves the data but then hangs and eventually crashes

**Comment by Hamilegit** [comment]
I was wondering why my valhelsia 3 server stops just before total shutdown, driving me nuts

**Comment by someaddons** [comment]
fixed in 72
