### ISSUE TITLE
Had this Bug for a while now and i coulden really figure out where it came from but blame says its performant

### ISSUE THREAD

**Issue by Mr-Syntax** [someaddons/performant_issues#176]
When i fly around in creative mode it works for a good bit but then i always get stuck on some chunks that are not loading and the server crashes
im on 1.16.5
forge 36.2.0

[crash-2021-07-29_02.33.42-server.txt](https://github.com/someaddons/performant_issues/files/6897152/crash-2021-07-29_02.33.42-server.txt)

**Comment by someaddons** [comment]
not seeing in the log where blame says its performant
