### ISSUE TITLE
The chunk not load

### ISSUE THREAD

**Issue by huyhhuy1410** [someaddons/performant_issues#179]
When i used this mod on my server, i tried to go anywhere and sometimes the chunk not load, i couldn't go anymore, i must leave and join the server again to load the chunk, but it happened many times. I removed the mod and everything normal. I don't know what causes this.

**To Reproduce**
1. Install the mod on both client and server side
2. Start the server
3. Play like normal
4. The chunk not load

**Expected behavior**
I just want to use this mod on server to optimize my server but it's not like i thought.

**Screenshots**
I have some screenshots:
![image](https://user-images.githubusercontent.com/86774570/127840799-487a98ab-4431-4e5d-bdd7-eff2af49bc89.png)

** Mod version **
performant-1.16.2-5-3.72m

** Logs **
https://mclo.gs/U6HXHjN

**Comment by someaddons** [comment]
is this only forge? or are you using some derivative like mohist etc?

**Comment by huyhhuy1410** [comment]
I'm using mohist

**Comment by MrJorman** [comment]
> I'm using mohist

you noob

**Comment by someaddons** [comment]
mohist does custom modifications which break stuff and is not supported as this is a forge mod
