### ISSUE TITLE
cacheRecipes breaks stonecutter recipes

### ISSUE THREAD

**Issue by nanonestor** [someaddons/performant_issues#18]
**Describe the bug**
Issue with config setting "cacheRecipes" breaking stonecutter recipies.  When set to true most recpies are no longer present.

If set to  "cacheRecipes = false" issue goes away and stonecutter works per normal.

**To Reproduce**
Toggled false/true/false/true to confirm.

**Expected behavior**
Recipes not being broken? lol

**Screenshots**
-

** Mod version **
-performant-1.15-3.11m.jar
-instance was run on a dedicated server MC 1.15.2

** Logs **
Latest/Crash log

**Comment by someaddons** [comment]
should be fixed in v3.12m
