### ISSUE TITLE
Crash on 1.16.5

### ISSUE THREAD

**Issue by XionioXMaster** [someaddons/performant_issues#182]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**

**To Reproduce**
1. I have no idea

**Screenshots**
nope

** Mod version **

performant-1.16.2-5-3.72m

** Logs **
[crash-2021-08-16_16.26.01-server.txt](https://github.com/someaddons/performant_issues/files/6993175/crash-2021-08-16_16.26.01-server.txt)

**Comment by someaddons** [comment]
not an issue caused by performant and mohist is not supported
