### ISSUE TITLE
Random server Crashes with error "java.lang.ArrayIndexOutOfBoundsException: -1"

### ISSUE THREAD

**Issue by dilsaajan** [someaddons/performant_issues#183]
Recurring crash on Forge 1.15 modded server when the multiEntities config under ["Entity settings"] is set to true. 
Never crashes when multiEntities set to false.

**To Reproduce**
1. Forge: forge-1.15.2-31.2.47.jar
2. Run a server
3. Mods: see https://www.mediafire.com/file/ojalydvlx4e4tjv/mods.zip/file
4. Crashes (seemingly) randomly, rolling back the server a few minutes

**Expected behavior**
No crashes

**Screenshots**
N/A

** Mod version **
1.15-3.16m

** Logs **
Crash log:
[crash-2021-08-07_00.41.12-server.txt](https://github.com/someaddons/performant_issues/files/7090156/crash-2021-08-07_00.41.12-server.txt)

Logs at that time:
[2021-08-07-32.log](https://github.com/someaddons/performant_issues/files/7090228/2021-08-07-32.log)

Mods (if not willing to download via MediaFire):
![image](https://user-images.githubusercontent.com/16635363/131653926-4084325c-56b3-4479-ac7a-45ab81115a3f.png)
![image](https://user-images.githubusercontent.com/16635363/131653980-5be51c2e-ea2e-4a3d-bb11-4340b28d8622.png)

**Comment by Trinsdar** [comment]
this looks like a multithreaded crash, something is trying to modify a list at the same time as something else, causing a conflict

**Comment by someaddons** [comment]
Can't reproduce, probably some other mod causing it
