### ISSUE TITLE
Hostile mobs spawning unusually infrequently when players are spread out

### ISSUE THREAD

**Issue by MaxWasUnavailable** [someaddons/performant_issues#186]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
Hostile mobs spawn far less when performant is enabled on a forge server.

**To Reproduce**
1. Have players online & spread out over an area.
2. Watch how some players barely have any hostile mobs spawn at night.

**Expected behavior**
Hostile mobs spawn for all players at night.
Removing performant from the modpack effectively fixed this; but tanked TPS to 10 - 15 during nights.

** Mod version **
performant-1.16.2-5-3.72m

**Comment by p1ut0nium-git** [comment]
Same problem here. Almost no hostile mob spawns when spread out.

performant-1.16.2-5-3.72m
forge 1.16.5-36.2.0

**Comment by someaddons** [comment]
fixed in 3.74
