### ISSUE TITLE
[1.16.5] Regular stocking / lag

### ISSUE THREAD

**Issue by TheSnowyChickens** [someaddons/performant_issues#187]
**Describe the bug.**
Hello, my bug is easy to explain

Performant installed on client+server:
some regular (maybe all 20seconds) hard, but very short, fps drops to 0. (a big red line in the alt - F3 graph)
Together with server lag and motion aborts.

Performant installed server side only:
the "same" hard fps drops, but a bit rarer. Together with server lag and motion aborts.
(example: with Tinkers slime sling + boots you can feel it very well)

At all:
a lot of "Can't keep up! Is the server overloaded? Running 2212ms or 44 ticks behind" all the time, the whole console is full with that.

**To Reproduce**
1. Setup a 100 mods modpack (IE + addons / Create as main tech mods)
2. Create a Bop worlds (in our case)
3. Solo on the server and with other people on the server noticeable

**Expected behavior**
A smooth alt + F3 graph.

** Mod version **
Forge: 36.2.5
Performant: 5-3.72m
MC: 1.16.5
No Optifine

** Logs **
Info: I can't use pastebin for the logs, because:
![grafik](https://user-images.githubusercontent.com/29357962/134088769-2289f088-90db-4ece-87ef-9f942a1f525b.png)

I need to upload the file, sry:
Log in the .zip file:
[2021-09-20-1.log](https://github.com/someaddons/performant_issues/files/7199157/2021-09-20-1.log)

Latest log:
[latest.log](https://github.com/someaddons/performant_issues/files/7199169/latest.log)
(we are a german community, so no worry about the non-english words in the chat ^^)

**Comment by someaddons** [comment]
fixed in 3.74
