### ISSUE TITLE
[1.16.5] Points of Interest (POI) data mismatch on world reload

### ISSUE THREAD

**Issue by SilverDavidMC** [someaddons/performant_issues#188]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
When a modded point of interest (POI) exists within a chunk, that POI will not be saved upon exiting and reloading the world unless a vanilla POI (beds, bells, villager workstations) also exists within the same chunk.

**To Reproduce**
1. Enter a chunk that has no POIs in it. Using a void superflat is the easiest.
2. Place a block with a modded POI in a chunk (Blue Skies' portals or Environmental's sawmill as some examples).
3. Leave the world.
4. Reload the world.
5. Break the blocks with POIs while looking at the console output.
6. If the chunk contains only modded POIs, the console should say "POI data mismatch" for the modded ones. Vanilla POIs should produce no error.

**Expected behavior**
POIs should always be saved in a chunk.

**Mod version**
Performant: 1.16.2-5-3.72m
Mods with POIs to test with:
- [Blue Skies 1.16.5-v1.1.3](https://www.curseforge.com/minecraft/mc-mods/blue-skies/files/3411324) requires [Structure Gel](https://www.curseforge.com/minecraft/mc-mods/structure-gel-api/files/3268432)
- [Environmental 1.16.5-1.1.0](https://www.curseforge.com/minecraft/mc-mods/environmental/files/3416597) requires [Abnormals Core](https://www.curseforge.com/minecraft/mc-mods/abnormals-core/files/3457851)

**Logs**
Error on line 350
[latest.log](https://github.com/someaddons/performant_issues/files/7211686/latest.log)

**Comment by someaddons** [comment]
fixed in 3.74
