### ISSUE TITLE
Just had this Crash on 1.16.5

### ISSUE THREAD

**Issue by Mr-Syntax** [someaddons/performant_issues#189]
I have made this pack and the only reason it can run is performant so thank you for that

but i just had this crash cant really identify if its Performant of Colds skunks tho
[crash-2021-09-27_15.46.51-server.txt](https://github.com/someaddons/performant_issues/files/7236715/crash-2021-09-27_15.46.51-server.txt)

its in this pack

https://www.curseforge.com/minecraft/modpacks/chosencraft

**Comment by someaddons** [comment]
Its the skunk mob crashing, performant only happens to run the ai
