### ISSUE TITLE
Server crash caused by Performant

### ISSUE THREAD

**Issue by Nqwq** [someaddons/performant_issues#190]
The server crashed when I used this mod, there are a lot of errors in the log about this mod, I hope the author can solve it and make it not crash, thank you,
The version of the mod is: Performant-1.16.2-5-3.72m
Attached is the log download link:
latest.txt:https://paste.ubuntu.com/p/JcpcNKgBj5/
The debug log: https://paste.ubuntu.com/p/Df7zh6zBvr/

**Comment by someaddons** [comment]
That is not a crash, just a warning of a bad loottable
