### ISSUE TITLE
1.16.5 | Server | Bad loottable added

### ISSUE THREAD

**Issue by EnderGamingFilms** [someaddons/performant_issues#191]
When running performant on a server there are console errors regard bad loot tables being added with a `null` name.

**To Reproduce**
Install performant on 1.16.5 server. If this does not reproduce the error contact me for a full list of mods I use or the server files I have.

** Mod version **
1.16.2-5-3.72m

** Logs **
https://hastebin.com/ugasinicif.sql

**Comment by someaddons** [comment]
Its a warning for a bad loottable added by a different mod, take the report to the mod in question
