### ISSUE TITLE
Serious memory leak when re-entering a world

### ISSUE THREAD

**Issue by LTCatt** [someaddons/performant_issues#192]
Version: performant-1.16.2-5-3.72m

Each time you quit to title and re-enter a world, the game's memory usage will increase.

-----

In addition to this Mod, I also installed Chunk Pregenerator. It provides a command "/pregen utils GC" which triggers Full GC, so I can get an accurate memory usage.

1. Enter the game for the first time, walk around a few times, and trigger Full GC. About 400M memory was used.

2. Quit to title and re-enter the game. Repeat 4 times, and trigger Full GC. About 1300M of memory was used.

If Performant is disabled and only Chunk Pregenerator are installed, the memory usage is 420M after repeating these steps, which is almost no increase from the beginning.

-----

In my modpack with 80 mods installed, each re-enter adds **MORE THAN 250M** memory usage.

When I changed map a few times at one point, I saw the game's memory usage increase from 1.2G to **OVER 3G**, which was horrible... So I went through all the mods using dichotomy and finally found that when this mod was disabled (other 79 mods are still enabled), this bug disappeared...

**Comment by someaddons** [comment]
fixed in 3.74
