### ISSUE TITLE
Customnpc Ai not working correctly if I have perfomant also installed (In 1.12.2 forge)

### ISSUE THREAD

**Issue by PorkingGit** [someaddons/performant_issues#193]
There's a bug in 1.12.2 where the customnpcs have broken ai with performant installed, happens in all mod versions (for both mods in 1.12.2)

To reproduce :

Create a custom npc, set its AI to either retreat, or panic, and faction to neutral(so you can hit it), and hit it, the npc is supposed to run away, but instead does completely nothing if I have performant installed as well. And if the npc is set to retaliate on its attackers, It can respond like 10 seconds after being hit..

**Comment by someaddons** [comment]
fixed in newest
