### ISSUE TITLE
Noticeable lag spike when garbage collection happens.

### ISSUE THREAD

**Issue by NickChamberlin** [someaddons/performant_issues#194]
I've installed around 90 mods at this point, when I remove performant the lag spike when garbage collection happens goes away. Is there any specific settings I should adjust to try to find the problem? I just tried removing all but around 19 mods and it's still doing it. I've tried 4gb, 6 and 8 gb of ram, same thing.

performant-1.16.2-5-3.72m

**Comment by someaddons** [comment]
fixed in 3.74
