### ISSUE TITLE
Server console spam

### ISSUE THREAD

**Issue by cpm9** [someaddons/performant_issues#195]
**Description**
Large server console spam... the first type is over a thousnad lines of "bad loot table added" error messages that are generated at server start up. The second type is a Mixin apply failed warning when Performant and Connectivity are present that appears once after server is done loading and once every time a player joins.

**To Reproduce**
1. Install performant and connectivity on forge server
2. Run server and observe console
3. Notice ~1250 lines of bad loot table messages
4. Notice Mixin apply failed message
3. Have player connect to server and observe Mixin apply failed message again

**Expected behavior**
I did not expect these large error and warning messages to appear when the server is starting and done loading and every time a player joins

**Mod version**
Minecraft 1.16.5
Java 8 - 291
Forge 1.16.5-36.2.6
Connectivity-2.3-1.16.5
Performant-1.16.2-3.72m

**Logs**
In the latest.log between line 247 and 1500 are the bad loot table messages. At line 1549 the Mixin failed message (server done loading) and line 1650 Mixin failed message (player joins)

[latest.log](https://github.com/someaddons/performant_issues/files/7406868/latest.log)

**Comment by someaddons** [comment]
The mixin apply failure is intended, they both do the same modification in that part and only one should apply. Bad loottable is a warning for when a mod adds an unnamed loottable, take it to the mod in question JAOPCA , performant is just the messenger.
