### ISSUE TITLE
Flying Mobs update rate

### ISSUE THREAD

**Issue by OfficialLambdax** [someaddons/performant_issues#197]
performant-1.16.2-5-3.74m.jar running on 1.16.5 with Forge 36.2.9.

This is almost certain not a bug but a feature. I just dont seem to find any option in the config to disable it for all or just certain mobs.

I want all or set mobs to not be affected by the update rate limitation.

https://www.youtube.com/watch?v=ZnbwwpKSs1c

Soon i want to add the Ice and Fire mod and those mobs too can be seen from a far. Just like in this case it would look very silly if they lag in the air like this.

Please tell me what i need to change in the config, because i see no option to toggle it (:

**Comment by someaddons** [comment]
`enableDynamicEntityUpdates` is the option to toggle it on/off, the range at which entities are throttled depends on those entities themselves, as each entity has their own activation range, which is set by the mod creating the entity, called `clientTrackingRange` in vanillas terms.

**Comment by OfficialLambdax** [comment]
Thanks ! im trying todo that and see if it works 👍

**Comment by OfficialLambdax** [comment]
Alright so toggling said option to false then starting the game and then loading a sp world shows a **bug**. The entities are now invincible. The same issue also exists on a server. The mob sounds can still be heared and also how they move, but they are invincible. A Game restart didnt fix it, but toggling the option **on the client** back to true did.

So the server has said option set to false and the client has it on true. Through this, the mobs are no longer invincible but the server calucalte the mobs like i desired (:

**Comment by OfficialLambdax** [comment]
So i did go so far and created a new minecraft instance with just performant-1.16.2-5-3.74m.jar running on 1.16.5 with Forge 36.2.9. And the issue is the same. The mobs are invincible. They can be heared, hit and interacted with but not seen.

https://www.youtube.com/watch?v=yLVsK7lJaLI

**Comment by someaddons** [comment]
ah indeed if you toggle off the dynamic updates then the rendering range thing isnt updated

**Comment by someaddons** [comment]
should be fixed in v3.75m
