### ISSUE TITLE
Invisible NPCs

### ISSUE THREAD

**Issue by Lumbago1337** [someaddons/performant_issues#198]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
With the latest version I can't see any NPCs. I only play singleplayer, so I don't know about real players.
When I revert back to version performant-1.16.2-5-3.72m.jar everything is normal again. I tested this with default performant settings.
I'm also not sure, if this has something to do with incompatibility with other mods. Let me know, If I have to test specific setups.

**Expected behavior**
Clear visible NPCs :)

** Mod version **
performant-1.16.2-5-3.74m.jar

** Logs **
https://gist.github.com/Lumbago1337/0d4d5483b76917c7b70e82e91f475f30

**Comment by someaddons** [comment]
try with `enableDynamicEntityRendering` config off, that one hides entities you can't see, may conflict with optifine

**Comment by someaddons** [comment]
might be fixed for you in 3.75m aswell

**Comment by Lumbago1337** [comment]
I've tryed it with the new version and also with enableDynamicEntityRendering off, but the issue is still present.
