### ISSUE TITLE
1.15.2 Performant breaks damage from sweet berry bushes

### ISSUE THREAD

**Issue by radiomike** [someaddons/performant_issues#20]
Sweet berry bushes are supposed to cause player damage and slow player down when walked into/through. With performant enabled, player is slowed down, but no damage is received.

**To Reproduce**
With performant enabled, walk into a sweet berry bush.

**Expected behavior**
Player damage should be received.

** Mod version **
performant 1.15-3.11m
forge 31.2.0/36/41

No crash so no log.

**Comment by SonicSpeedster16** [comment]
I can also reproduce this. Walking through sweet berry bushes slows the player down but causes no damage with Performant installed.

Minecraft 1.15.2
Forge 31.2.43
Performant 3.11m

**Comment by someaddons** [comment]
fixed in 3.13m
