### ISSUE TITLE
Paintings instantly stop rendenring when placed

### ISSUE THREAD

**Issue by AutumnalFox** [someaddons/performant_issues#200]
When placing entities like paintings and item frames they render for like half a second then stop rendering at all, so the block it's still there but not showing up. Seems to be a problem with the lastest build for 1.16.5 (performant-1.16.2-5-3.75m.jar) since I downgraded to the previous build to test and paintings/frames start working again as they should. I also tested in both forge 36.2.4 and the most recent one, forge 36.2.9, to see if that was the problem but no difference in results.

** Mod version **
performant-1.16.2-5-3.75m.jar (Lastest 1.16.5, Nov 9 2021)

I'm also including the 36.2.4 log just in case you wanna see it:
[36.2.4.log](https://github.com/someaddons/performant_issues/files/7504952/36.2.4.log)
[36.2.9.log](https://github.com/someaddons/performant_issues/files/7504953/36.2.9.log)

**Comment by DerekM07** [comment]
Also having this issue with 3.75m on MC 1.16.5--tested both Forge 36.1.0 and Forge 36.2.0.

**Comment by ksk-waqs** [comment]
I also confirm the problem. performant-1.16.2-5-3.75m.jar, forge 36.2.2

**Comment by Bindon10** [comment]
You may be able to mitigate this bug for the moment by setting enableDynamicEntityRendering = false in your config
I had this issue with Minecarts and fixed this same issue by doing what I suggested.

**Comment by someaddons** [comment]
should be all fine again with 3.76m :)
