### ISSUE TITLE
[1.16.5] Falling blocks are invisible while falling

### ISSUE THREAD

**Issue by Charnuz** [someaddons/performant_issues#201]
Any falling block entity (sand, anvils, etc) is invisible while falling, but lands on the ground just fine. Did test with this being the only installed mod and it still happens, and does not happen if not installed.

** Mod version **
Forge: 36.2.9
Performant: 1.16.2-5-3.75m

** Logs **
[latest.log](https://gist.github.com/Charnuz/6df1dee3b43c65cd1f66e2b2a5097fb9)

**Comment by harmalom** [comment]
Something similar happens to me with the frame items, when I place them, they become invisible and all items placed in them become invisible as well.

**Comment by someaddons** [comment]
should be all fine again with 3.76m :)
