### ISSUE TITLE
[1.16.5 feature request] Addional options for the dynamic rendering

### ISSUE THREAD

**Issue by SteamDoge9000** [someaddons/performant_issues#206]
Hello, this is not really a bug, but more of an idea. while I have notices some things phazing in and out and is aware of this being a consiqence for better performance, I was wondering if some more dynamic settins could be added to this
what I have in mind follows:

*an ability to configure what mobs will not be effected by the dynamic render option (if its in this list, any entity render will be blacklisted from its dynamic render sysstem) this would be great for things like item frames and certan entities that you dont want to phase out ro be affeced by the dynamic render system, will be empy by default

The wahy taht I hope this would work is as simple as providing the name of the enity into the list

For example, if I dont want the fire dragon from ice and fire to have its render disapear when fighting it, putting in the entity's id "Iceandfire:firedragon" it would blacklist and prevent the dynamic render system added by this mod to not be used and allow for its normal rendering behavior to take place

I would NOT recoment a whitelist option to this for it can be a major pain todo it in a whitlist setting, especahly for those with large modpacks that adds lots of entites

hope you like this idea and its possable todo, this mod is the reason im able to play in an FPS intesive area

**Comment by SteamDoge9000** [comment]
Addional option, 
Dynamic Render Dim Blacklist (optional, disabled or blank by default) adding a dim into this list will exept it from the optimization from running, useful if you have a mod like MCDOOM present and some of the enties dont render till your close enough to them

**Comment by someaddons** [comment]
ye I can see this beeing useful, gonna add some options

**Comment by someaddons** [comment]
added in 3.79m, also made the time it takes to be hidden smarter, it'll take the entities own distance setting into account so you may not even need to blacklist them now
