### ISSUE TITLE
server down 1 16 5 3.77m

### ISSUE THREAD

**Issue by DonorKrovi** [someaddons/performant_issues#207]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**

**To Reproduce**
1. i dont know

**Screenshots**
nope
** Mod version **
3.77m

** Logs **
[Latest/Crash log](https://gist.github.com/DonorKrovi/0e1166b0cac991785e52c55a2995e673)

**Comment by XionioXMaster** [comment]
I have a similar problem, I don't understand what causes it> Moreover, how to find out

**Comment by someaddons** [comment]
fixed in 3.78
