### ISSUE TITLE
Setting just fastCollisions false results in crashes

### ISSUE THREAD

**Issue by radiomike** [someaddons/performant_issues#21]
**Describe the bug**
When just fastCollisions is set to false in config game will crash when in world. In existing world crash seems to happen while world is rendering. With new world, crash will occur shortly after starting world and moving around a bit. All other config options are left as default.

**To Reproduce**
set fastCollisions to false.
Start/create, a world.

**Expected behavior**
fastCollisions should disable and crash shouldn't occur.

** Mod version **
performant 1.15-3.11m

** Logs **
https://gist.github.com/radiomike/b2b40e5effd9378ff9f5a400cf672d27

**Comment by someaddons** [comment]
fixed
