### ISSUE TITLE
[1.16.5] Update is incompatible with OTG mod.

### ISSUE THREAD

**Issue by ProsperCraft** [someaddons/performant_issues#210]
**To Reproduce**
Install Forge 1.16.5 .20
Install OTG
Install Performant
Run and crash on launch.

**Expected behavior**

**Screenshots**

** Mod version **
OpenTerrainGenerator-1.16.5-0.1.7
performant-1.16.2-5-3.80m

** Logs **
Latest/Crash log
https://gist.github.com/ProsperCraft/5f2ef8e054964bf108bed167f184eb6e

**Comment by ProsperCraft** [comment]
OTG said they added a mixin with the last update.

**Comment by someaddons** [comment]
Well they added a mixin for a similar modification performant does, out of which naturally only one is applied/needs to be applied and OTG is then crashing when their mixin is not able to apply.

**Comment by ProsperCraft** [comment]
Fixed on OTG side :)
https://www.curseforge.com/minecraft/mc-mods/open-terrain-generator/files/3566049

**Comment by someaddons** [comment]
nice :)
