### ISSUE TITLE
Excluding Entities inside config causes Startup Crash!

### ISSUE THREAD

**Issue by ReeCodes** [someaddons/performant_issues#211]
Crash on Startup because of changes to the config

**To Reproduce**
1. Start MC

**Expected behavior**
Run flawlessly

** Mod version **
performant-1.16.2-5-3.80m.jar

** Logs **
[crash-log] https://mclo.gs/VqQ0uau
[Latest log] https://mclo.gs/FpbVpBM
[performant-common.toml] https://mclo.gs/52GLXMv

**Comment by someaddons** [comment]
don't see anything related to performant in those logs, nor is the crash it has related to any performant function, so I'm pretty sure this is a case of `Correlation does not imply causation`

**Comment by someaddons** [comment]
fixed in 3.81m
