### ISSUE TITLE
Recomendation: same as the last one I made, but with mobs and their AI's

### ISSUE THREAD

**Issue by SteamDoge9000** [someaddons/performant_issues#212]
**Describe the Recommendation**: Remember when I made the recomendation to have an option to exclude certain entities form the dynamic render system? Theirs a possable issue that this mod may conflict with Atums's Ai and creating a possable memory leak as a responce. While I have not confimred this as of this time, I came across the thought of why not adding a blacklist for mobs that are in this list to be excluded from any sort of AI optimizations (if possable) that this mod provides. I think it would be a good idea in case this mod for some reason causes "head-on" issues with other mobs where this mobs AI improvments could break their ability to fuction and create unforseen problems

To the point: Please add a blacklist for when an entity ID is in this list that it would be excldued (if possable) by this mods AI optimizations; if you want to go even farther you could even include addional paramiters per listed item to describe what certain AI enhancing features provided by Performant will be disables; this will allow for more cusomization and a work around for mods that has mobs with AI that would potently suffer from these optimizations.

if you liked the idea I had last time, then this I hope will also be a good idea, provided if this can even be done.

Thanks again for taking your time to read this and have a nice day ^w^

**Comment by SteamDoge9000** [comment]
if this is idea accepted, It would be also a good idea to  include an example in the description of sed option that would include a plain example, an example for affecting any mob from a mod (Ie, modNamehere:*) and an example that would demonstrate additional parameters (if you decide to go this route that is along with this idea) to what specific functions would be disabled in the AI optimizations instead of completely disabling all optimizations to sed mob's AI (this would by defualt be done if no additional parameters are given; Ie, modnamehere:MobA [disables all AI opimizations for sed mob],  modNameHere:Mob_B, {pannic, breed} [only disables optimizations made from the "panic" and "breed" opimizations if present on the mob listed])

**Comment by someaddons** [comment]
performant only touches very few vanilla AI's and none of the modded AI's, if there is any issue its a bug and should be simply reported, there really isnt a reason to disable them, nor can you do it nicely for just some either
