### ISSUE TITLE
singlePlayerWatchDogTimeout should be disabled by default

### ISSUE THREAD

**Issue by Speiger** [someaddons/performant_issues#213]
Ok this is a bugreport from a "Laggy" Mod that is laggy intentional.

I get these Bugreports: "Chunk Pregenerator Crashes the game because it lags the game to much".
Yes it lags the game to much because minecraft forces to save all chunks that changed no matter how slow I reduce it.
This is a design flaw in minecraft. But the 3 minute Timeout is to little thanks to minecrafts design flaw.

I am generating in batches of 1024 chunks (32x32 which is roughly 60x60 so minecraft will forcefully save all of them)
to make the best use of all the offthread worldgeneration. 
And since minecraft forces to save all chunks no matter the lag (yes even vanillas server is triggered) performants ServerWatchdog is triggered.

So yeah... I will write out a Performant information to disable this config by default because it is stupid in the first place.
(Especially if you add a custom integrated server that is running independent of the game to make a preview map and then the game gets killed because of this performant mod that wants add a default kill switch)

Also even if you ignore my "Suggestion". 
here is another: Name the Thread: "Performant Integrated Server Watchdog" so people don't have to search for 3 days to find out who added this feature and can look at the options...

We only found out about this by Binary Searching the Game with Visual VM in a Giant ModPack...

**Comment by someaddons** [comment]
Due to unwarranted hostility and disrespectful tone I'm just going to close this, if you're interested in a solution you're free to reword it in a more respectful manner and make a new post

**Comment by Speiger** [comment]
No worry. It will be addressed in the next patch from my side.
