### ISSUE TITLE
Crash server Citizen NPC plugin

### ISSUE THREAD

**Issue by DonorKrovi** [someaddons/performant_issues#214]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**

**To Reproduce**
If you create NPc, / npc create
then point it to / npc path the server will crash. I am using loliserver as my server core

** Mod version **
3.81

** Logs **
https://gist.github.com/DonorKrovi/437dd5fcdc4f22534faf934162d374c1

**Comment by XionioXMaster** [comment]
same

**Comment by someaddons** [comment]
that is caused by loliserver not performant
