### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 257

### ISSUE THREAD

**Issue by XionioXMaster** [someaddons/performant_issues#216]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**

**To Reproduce**
1. I have this when generating a world with the Better End Reforked mod

** Mod version **
3.81m

** Logs **
[Latest/Crash log](https://gist.github.com/XionioXMaster/2daa667b07de4371673be65301515f5d)

**Comment by someaddons** [comment]
Seems to be a loliserver issues again, and I only support pure forge anyways
