### ISSUE TITLE
Mixin related crash at server startup. 1.16.5 performant-1.16.2-5-3.82

### ISSUE THREAD

**Issue by grisha252** [someaddons/performant_issues#217]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**

Server start up fails with Performant installed.  Log below.

**To Reproduce**

**Expected behavior**

**Screenshots**

** Mod version **
performant-1.16.2-5-3.82

** Logs **
Latest/Crash log
[debug.log](https://github.com/someaddons/performant_issues/files/7834113/debug.log)

**Comment by someaddons** [comment]
Roadrunner is crashing, not performant

**Comment by grisha252** [comment]
Thanks.  When I take performant out, everything works fine.  I would love to use both.

Do they conflict?

Gary

**Comment by someaddons** [comment]
they apply the same modification there, just roadrunner crashes when theirs cannot apply.
