### ISSUE TITLE
crash server, twilight forest

### ISSUE THREAD

**Issue by MrJorman** [someaddons/performant_issues#221]
the server crashes after some time. log: https://pastebin.com/Gf8zBQYc

Please help.

My config: https://pastebin.com/PGg1G2g8

**Comment by MrJorman** [comment]
[crash-2022-01-27_23.01.25-server.txt](https://github.com/someaddons/performant_issues/files/7962684/crash-2022-01-27_23.01.25-server.txt)

**Comment by someaddons** [comment]
ah ye the server just crashed waiting on a chunk to load, probably sth either tried too load many chunks in one tick, or the specific loading was too slow for some reason. Both are unrelated to performant though, so closing this
