### ISSUE TITLE
[1.16.5] entities far away "glitch" and shutter 

### ISSUE THREAD

**Issue by SteamDoge9000** [someaddons/performant_issues#224]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
the issue is quite simple, 
![image](https://user-images.githubusercontent.com/38770780/153223189-225939ff-b80c-42d8-ad96-0c06a832312c.png)
entities that are a distance will cause them to glitch out and shutter
**To Reproduce**
1. for the best results, use an ice and fire sea serpent (make sure dynamic entity rendering is off to see this and have a high render distance (12 for best results)
2. summon it 120 blocks away and in the air (ex; /summon iceandfire:sea_serpant ~ 100 ~120 )
3. you will see it move slowly but its not supposed to shutter like that
4. tinker with the settings to see if the issue would occur with areas that you can conclude might be causing the issue (such as dynamic entity ticking and set the distance vale on that to 0 in the other thing that goes with it)

**Expected behavior**
the issue that I saw was the entity not moving and repeating animation frames when it shouldn't, after breaking down my large modpack I managed to isolate that this is an issue with Preformant. I tried disabling most of the setting where this might happen, including dynamic entity ticks, but nothing worked unless I removed the mod. Could you please take a look at it, 

**Screenshots**

** Mod version **
Your mods version: performant-1.16.2-5-3.84m.jar

** Logs **
Latest/Crash log
N/a, but will provide one if requested and deemed necessary for this issue

**Comment by someaddons** [comment]
That is normal behaviour of the enableDynamicEntityUpdates feature which ticks further out entities less, a more sophisticated version of simulation distance which 1.18 has. Just the config to disable it was accidently not taking effect, fixed in 3.85m
