### ISSUE TITLE
performant-1.16.2-5-3.85m Endlessly spawning bees

### ISSUE THREAD

**Issue by EightManEmpire** [someaddons/performant_issues#225]
Bees endlessly spawn at natural hives rendering the world unusable within seconds.

**To Reproduce**
1. Create world
2. Find natural generating hive
3. Endless bees spawn

**Expected behavior**
The bees to perform as if it was still a vanilla game.

**Screenshots**
![image](https://user-images.githubusercontent.com/73714851/153340264-5ec3f082-28cb-445f-9a51-74a61ac5e243.png)

** Mod version **
performant-1.16.2-5-3.85m

** Logs **
[latest.log](https://github.com/someaddons/performant_issues/files/8038198/latest.log)

**Comment by someaddons** [comment]
![image](https://user-images.githubusercontent.com/38401808/153404950-bd75a21c-1f72-4dd6-8048-7a41f2954031.png)
Canot reproduce it at all, which other mods are you using?

**Comment by Shizzins** [comment]
I believe he's using the MCMT mod which is multithreading and greatly improves server performance. This combined with performant is extremely effective but unfortunately causes thousands of mobs to spawn aggressively. There were over 3000 in one chunk

**Comment by someaddons** [comment]
MCMT is going to always break no matter what, mods are not written to work with it

**Comment by someaddons** [comment]
ye has mcmt installed, closing this then
