### ISSUE TITLE
Start Crash: Hinting to Performant

### ISSUE THREAD

**Issue by ReeCodes** [someaddons/performant_issues#227]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
MC Start Crash

**To Reproduce**
Start MC

**Expected behavior**
Run happily

**Screenshots**
![image](https://user-images.githubusercontent.com/50622547/154109898-ccd8d7ca-ddec-4693-93e7-6fbbe15b432c.png)

** Mod version **
performant-1.16.2-5-3.85m

** Logs **
[Latest/Crash log](https://mclo.gs/ZzuHj4v)

**Comment by someaddons** [comment]
yea forge broke some stuffs, fixed in 3.86m
