### ISSUE TITLE
[Bug]: Causes Arclight to crash

### ISSUE THREAD

**Issue by Elspar2** [someaddons/performant_issues#230]
### Describe the bug you're experiencing

Server crashes when Arclight and Performant are used together.
Arclight combines forge and spigot like Cauldron used to.
May not be possible to fix, but just reporting in case you want to add compatibility.

### Reproducability

Use arclight and performant.
Launch server.
Arclight fails to start which causes server to crash.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

https://gist.github.com/Elspar2/fd3ee223301796f284ca795164382fd2

**Comment by someaddons** [comment]
that is actually on arclight to fix, performant does not crash when its mixin cannot apply
