### ISSUE TITLE
[Bug]: Incompatability with "Does it tick?" mod

### ISSUE THREAD

**Issue by Ced7032** [someaddons/performant_issues#231]
### Describe the bug you're experiencing

When both mods are installed, hostile mobs do not spawn.

### Reproducability

Install Performant and Does it tick?.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

https://gist.github.com/Ced7032/02830c560d15256855bc529e1e232e88

**Comment by someaddons** [comment]
Does it tick mod is not supported in any circumstances, they're without any allowance whatsoever copying decompiled performant code and thus violating performants license.

**Comment by someaddons** [comment]
ye, well its usually a bad sign when the mod page has some stupid meme on them already :D
