### ISSUE TITLE
[propose] Chunk optimization

### ISSUE THREAD

**Issue by XionioXMaster** [someaddons/performant_issues#233]
### Describe the bug you're experiencing

I propose to add a fix for lags when transitioning between chunks, this is a very good opportunity to add optimizations for the game! If you do not understand what I mean, then here is an example of a mod

https://youtu.be/Wee5Rct6b_k

https://github.com/mjwells2002/ForgetMeChunk

The mod that solved it

### Reproducability

/

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

nope

**Comment by someaddons** [comment]
Doesnt seem like its needed in 1.18 and someone else already made a mod for it, so not going to integrate it myself

**Comment by XionioXMaster** [comment]
> Doesnt seem like its needed in 1.18 and someone else already made a mod for it, so not going to integrate it myself

This mod is for Fabric
