### ISSUE TITLE
[Bug]: Incompatibility with Sponge 1.16.5, instant crash on world load

### ISSUE THREAD

**Issue by TheOpalium** [someaddons/performant_issues#237]
### Describe the bug you're experiencing

Please refer to the following issue from Sponge's repo: https://github.com/SpongePowered/Sponge/issues/3667

In short: Performant is incompatible with Sponge due to some Mixin issue. This leads to the server immediately crashing on startup when both mods are present.

See crash log below.

### Reproducability

Start a 1.16.5 Forge server with the latest SpongeForge 1.16.5 (RC1112 at the time of writing) as well as the latest Performant (3.95 at the time of writing) and watch the server go boom.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

https://gist.github.com/TheOpalium/d609836758c17535e6c33a9189a1de8c

**Comment by someaddons** [comment]
First I'm generally not supporting alternate modloaders/API's as its a mod written for pure forge. I could potentially add a workaround here, but the reason its crashing is that sponge decides the mixin should crash when it cannot apply. If it was  performant's not applying you'd just see a log error.
It is also a pretty weird modification for an API, I dont really see why they need such a convenience modification
