### ISSUE TITLE
[Bug]: Quark leash incompatibility

### ISSUE THREAD

**Issue by LarsMans64** [someaddons/performant_issues#239]
### Describe the bug you're experiencing

The tie leads to fences function from quark can lead to a frozen game when fixLeash is enabled
performant-1.16.2-5-3.95m
Quark-r2.4-322

### Reproducability

Take 2 leads, tie 1 to a fence, then tie the other one to an entity (i used a chicken). When you try to tie the chicken to the fence the other leash is on, the game freezes and you won't be able to pick up items and entities don't move anymore. This doesn't happen when fixLeash is disabled.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

https://gist.github.com/LarsMans64/a025a9a518d52e32bdce453f4d7d0b25

**Comment by someaddons** [comment]
Looked into it this is just a plain quark bug, you can reproduce it without performant, gonna open a report there

**Comment by someaddons** [comment]
oh you're even out of luck, its a know bug and won't be fixed: https://github.com/VazkiiMods/Quark/issues/3453
