### ISSUE TITLE
[1.15.2] Ticking entity crash when paired with Aquaculture.

### ISSUE THREAD

**Issue by DenneyLewis** [someaddons/performant_issues#24]
**Describe the bug**
Suffering crashing issues with Aquaculture. This is happening because a ticking entity. I began to scale my mods back, and found that this is happening with just base vanilla too. For some reason Performant doesn't like fish very much. 👍 
**To Reproduce**
It's very random, but it seems like the more you're around fish, the more likely the crash can occur.

**Expected behavior**
Performant should not crash Minecraft.

**Screenshots**
N/A

** Mod version **
1.15-3.11

** Logs **
Crash log from the modded server (i don't have the vanilla one. :( )
[crash-2020-10-01_01.19.47-server.txt](https://github.com/someaddons/performant_issues/files/5314171/crash-2020-10-01_01.19.47-server.txt)

**Comment by MeinKraft** [comment]
i get the same ticking entity but for vanilla dolphins

forge 31.2.45
Performant 1.15-3.11m

[crashlog.txt](https://pastebin.com/Dv3cvwe0)

**Comment by DenneyLewis** [comment]
Server crashed 2 times today because of Ticking Entity. Having 2-3 crashes per day now. Somedays as many as 4-5 server crashes caused by this issue. 
[crash-2020-10-07_20.47.19-server.txt](https://github.com/someaddons/performant_issues/files/5345009/crash-2020-10-07_20.47.19-server.txt)
[crash-2020-10-07_22.19.08-server.txt](https://github.com/someaddons/performant_issues/files/5345010/crash-2020-10-07_22.19.08-server.txt)

**Comment by GoldenAlpharex** [comment]
To add on this issue, it doesn't happen solely with Aquaculture fishes. I disabled Aquaculture fishes spawning and it still crashes with Vanilla fishes. I do have to say that it is _very_ game-breaking and super annoying, losing progress every time it crashes and having to spend five or so minutes waiting for the game to load back up again.

**Comment by DenneyLewis** [comment]
It's getting out of hand. Having 8+ server crashes daily. Mod maker has been radio silent on any GitHub issue lately, so I don't think this is going to be getting fixed. I guess I'm just going to have to remove performant, but my players are getting tired of the server crashing so frequently. :(

**Comment by tomato3017** [comment]
Also having this issue multiple times daily on our server.

**Comment by cronix91** [comment]
Having the same issue, crashing every 10-30 min.  Hope it can get fixed soon..

**Comment by elienaimg** [comment]
I had this issue too... In my case I've solved the issue by using the config from this mod to forbid the mob causing crashes from spawning.  

Go to the mod's config file,find this line:
     forbiddenMobs = []
Should be the last line.. add the name of the entity to remove ( search"Entity being ticked" in your crash report)
In my case was the salmon from vanilla,so right now it  is like this in my config:
     forbiddenMobs = ["minecraft:salmon"]

**Comment by someaddons** [comment]
should be fixed in v3.12m

**Comment by Blue0Dwarf** [comment]
Experienced the same crash using v3.12m for Minecraft 1.15.2

[crash-2020-11-18_21.01.45-server.txt](https://github.com/someaddons/performant_issues/files/5564099/crash-2020-11-18_21.01.45-server.txt)
