### ISSUE TITLE
[Bug]: displayTooLargePackets not working correctly

### ISSUE THREAD

**Issue by xieve** [someaddons/performant_issues#240]
### Describe the bug you're experiencing

displayTooLargePackets was set to false in the config file, yet the warning still appears in the console.

### Reproducability

Set the config, install the New Tardis Mod which reproducably throws this warning when you're around or inside an open Tardis.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

https://oshi.at/hNwG/latest.log

**Comment by someaddons** [comment]
fixed in newest
