### ISSUE TITLE
Config clarifications and "disableNotifyOnBlockChange" config comment

### ISSUE THREAD

**Issue by NopeDK** [someaddons/performant_issues#241]
The default `#Disables block changes notifying all entity paths in the world, to possibly adjust their paths, disable with IE, incompat, default = true` is unclear. The first two sentences are clear, but the comma and continuation with `, disable with IE, incompat` needs clarification. Is this a reference to another mod, setting or something else entirely?

A short disadvantage/impact/side effects comment on settings would be appreciated. E.g.  What does the slower, default spawn interval affect? Does the above block notify mess with pathfinding (as a previous issue mentioned with villagers) or have any other side effects?

Inconsistent use of `, default =`, `. default =`, `. Default =`, `. default:`, etc., at the end of comments.

**Comment by someaddons** [comment]
fixed in 3.99
