### ISSUE TITLE
[Bug]: Mixin error & Lootpool error

### ISSUE THREAD

**Issue by FCKJohni** [someaddons/performant_issues#243]
### Describe the bug you're experiencing

When the server is started and it enters the Preparing spawn area phase, Performant throws a Mixin error. A Performance impact or anything similar is not noticeable.

You will also see a few Lootpool related errors during Server Startup

### Reproducability

I am not sure how to reproduce it, I am guessing it happens because of a Modcombination we have, but I am unsure.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

https://gist.github.com/FCKJohni/064950a3ecfa91c4134c34241c44ac6e

**Comment by someaddons** [comment]
The lootpool errors are warnings about a mod adding unnamed pools and don't affect the gameplay. The inject errors comes from using magma instead of forge which changes the source coding making it unable to apply a change. Non-forge code bases are not supported
