### ISSUE TITLE
[BUG 1.18.2] invisible mobs in boats/minecart/seat

### ISSUE THREAD

**Issue by MrJorman** [someaddons/performant_issues#244]
### Describe the bug you're experiencing

When I put the Performant 1.18.2 mod on the client, then when the mobs get into a boat or other transport or on the seats, then when I leave this chunk and come back again, the mobs become invisible.

### Reproducability

When I put the Performant 1.18.2 mod on the client, then when the mobs get into a boat or other transport or on the seats, then when I leave this chunk and come back again, the mobs become invisible.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

no logs

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/173973797-210b90d1-70fb-40d5-b024-661dcc2ea575.png)

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/173973811-0f194adc-042d-4cdf-ac47-78dbf584a8ed.png)
broken boat

**Comment by MrJorman** [comment]
In the config, I turned off all the functions for the test, but it didn't help either.

**Comment by someaddons** [comment]
fixed in the newest version 6.7 thanks for the detailed report :)

**Comment by GitJhopa** [comment]
> fixed in the newest version 6.7 thanks for the detailed report :)

Please give me a performance 1.18.2, I can't buy a subscription since I'm from Russia
