### ISSUE TITLE
[Bug]: 1.18.2 Server hangs on crash

### ISSUE THREAD

**Issue by mja00** [someaddons/performant_issues#245]
### Describe the bug you're experiencing

Whenever my server crashes (for various reasons, mostly my players doing dumb things), the server never fully exits properly and always hangs on a Performant based error. Doesn't seem like a specific crash causes Performant to hang the server, just any crash. I've had it happen with ticking world and a player creating a spell from a mod that's too strong.

I know Performant isn't crashing the server but just not letting it actually exit so my auto crash detection doesn't kick in. 

### Reproducability

Play the game and then somehow get it to crash and generate a crash report. 

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

https://gist.github.com/mja00/247404b4dbcb9bf26bb8157e542c4b57

**Comment by someaddons** [comment]
are you sure its performant stalling the server? Because the log messages at the end mean that performant stopped all threads that were still running due to the crash

**Comment by someaddons** [comment]
What you could try is adding : https://www.curseforge.com/minecraft/mc-mods/shutdowner to the server, as it detects shutdown hangs and prints out the stalling threads to the log/kills it off afterwards

**Comment by someaddons** [comment]
any new logs on this?

**Comment by mja00** [comment]
Yeah, I don't think my players have crashed the server, or at least it doesn't hang anymore since I installed Shutdowner. So I think it's safe to assume it was most likely a different mod causing the crash and I just assumed it was performant. Appreciate the mod recommendation and assistance.
