### ISSUE TITLE
[Bug]: Exorbitant use of ram on server

### ISSUE THREAD

**Issue by TainanRezende** [someaddons/performant_issues#246]
### Describe the bug you're experiencing

your mod on my server it starts loading loading things in ram until the limit until it freezes and crashes.

modpack: https://www.curseforge.com/minecraft/modpacks/techmagic-4/files/3834050 

the version of your mod I use is:performant-1.16.2-5-3.98m.jar

I still haven't updated the server pack until I solve this memory problem

### Reproducability

as we are playing on average 10 people the server starts and dps of a time 3 hours and the server is hitting 10gb of ram and without your mod this does not happen.

obs: this intensifies as the crowd advances (exploring, doing automation, etc)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

https://gist.github.com/TainanRezende/47e7262cca9f41c8d76de54289f2c5a7

**Comment by someaddons** [comment]
can't reproduce this with just performant, so must be some kind of mod conflict

**Comment by TainanRezende** [comment]
I've been testing some disabled configs, most of them take the server to increase the use of memory, and highlighting this problem becomes apparent as players advance in the game: they make bases, explore and evolve in mods

[performant-common.txt](https://github.com/someaddons/performant_issues/files/9003015/performant-common.txt)

this is the config I'm using, most of the features are disabled due to if I activate them, the ram memory goes up and doesn't go down, reaching the limit and freezing the server, the way I left it in the current config it reaches 7.8gb and but soon after this to 5 there it is in this loop of up and this

**Comment by TainanRezende** [comment]
I'm going to ablitar all the confg and wait for the freeze and send the log here
