### ISSUE TITLE
[1.12.2] Perfomant makes Minecraft crash at start up.

### ISSUE THREAD

**Issue by pvini07BR** [someaddons/performant_issues#25]
I dont know if this is a conflict with another mod, but, when i start Minecraft, forge starts loading, and after some seconds, Minecraft crashes. The log dosen't tells what mod caused the crash, but when i removed Perfomant from the mods folder, it dosen't crashed anymore.

I'm also using the VanillaFix mod, so basically, when Minecraft crashes at start up this appears:
![image](https://user-images.githubusercontent.com/27783608/95359428-855a2880-08a0-11eb-883e-cf00bb903b5d.png)

And there is the crash log:
https://gist.github.com/pvini07BR/e04b252d636022d8b4d6c7c863460996

Also in the crash log, there is an list of the mods i am using.

**Comment by DiogoHSS** [comment]
if this is the same as mine, mods using different versions of mixin, I fixed it by downloading Mixin 0.7-0.8 Compatibility from https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility

**Comment by someaddons** [comment]
1.12 isnt getting support anymore

**Comment by Liberateur** [comment]
> if this is the same as mine, mods using different versions of mixin, I fixed it by downloading Mixin 0.7-0.8 Compatibility from https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility

THANKS GUY <3 !
