### ISSUE TITLE
Invisble Mobs in boat/ 6.7 Version Crashes Game

### ISSUE THREAD

**Issue by Doku-Kitsune** [someaddons/performant_issues#251]
Hello, I downloaded the mod for my 1.18.1 world and the 6.3 version had mobs invisible in the boats. I noticed this was resolved in the 6.7 update. So I downloaded that and when I went to launch my world my game crashed. Please help.
![16580326464065400133252675088322](https://user-images.githubusercontent.com/98247583/179384147-ad6b14d3-0733-407e-8a63-38fe684ef7cc.jpg)

**Comment by someaddons** [comment]
hey, the 6.7 version is for minecraft 1.18.2 thats why it crashes. I'll probably not get around to porting all the stuff to 1.18.1 as its a small,dying inter-version so I'd either say stay on 6.3 or upgrade to 1.18.2 Minecraft
