### ISSUE TITLE
[Bug]: Mob variants are all the same on servers with performant beta 1.18.2-6.7

### ISSUE THREAD

**Issue by Coda1552** [someaddons/performant_issues#252]
### Describe the bug you're experiencing

I went into a server without performant on the server, and variants were fine. Upon adding performant to the server, mob variants get messed up and appear to be all the same (tropical fish, for example). Having performant on the client doesn't seem to make a difference.

### Reproducability

Go into a server with performant and spawn tropical fish or other entities with variants, they'll all be the same.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

https://gist.github.com/Coda1552/48eedaf8c0d71305277dc8f889fcc54a

**Comment by Coda1552** [comment]
The bug is affecting me but not my friend with the same mods on the same server. Only difference is forge version. He has 40.1.31 and I have 40.1.68.

**Comment by someaddons** [comment]
hey, I can't seem to reproduce it with either forge version
![image](https://user-images.githubusercontent.com/38401808/182043260-a8401807-aeed-4e7c-bd85-9874974dee58.png)

**Comment by Coda1552** [comment]
Oh, weird. Thanks for looking, anyways :)
