### ISSUE TITLE
[Question]: Compatible with FastSuite?

### ISSUE THREAD

**Issue by Chaos02** [someaddons/performant_issues#253]
### Describe the bug you're experiencing

Hey I've just been wanting to ask if this is compatible with FastSuite as this mod also implements recipe caching but with a hotspot algorithm.

If not, please make this feature able to be turned off!
Regards, thanks, Chaos

### Reproducability

\

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

\\

**Comment by someaddons** [comment]
as both do recipe stuff either one takes priority, or it ends up crashing, not sure never tried. Anyways you can turn it off with the "cacheRecipes" config value. But with performant you dont really need fast suite at all
