### ISSUE TITLE
[Bug]: Add option to exclude spiders of fast collisions

### ISSUE THREAD

**Issue by RaulMARK17** [someaddons/performant_issues#254]
### Describe the bug you're experiencing

In the 1.16.5 version, there is a mod, spiders 2.0, it's great, but is not compatible with fast collisions and multithreading movements of mobs. It's posible to exclude spiders from multithreading, but not of fast collisions, so please, give an option to exclude spiders and cave spider from it. 

### Reproducability

Install performant and spiders 2.0 in minecraft 1.16.5

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

https//:nothing_here

**Comment by someaddons** [comment]
Not going to add compat to a mod that is far too laggy and no longer maintained

**Comment by Deepfriedyag** [comment]
> Not going to add compat to a mod that is far too laggy and no longer maintained

You don't have to add compat just make it so we can blacklist any entities we want in the configs. Pretty sure it isn't just this particular mod that performant entity features break.
