### ISSUE TITLE
[Bug]: Hiper flood (1.16.5)

### ISSUE THREAD

**Issue by viminio** [someaddons/performant_issues#256]
### Describe the bug you're experiencing

A large flood, does not affect server performance, but makes it difficult to read logs

### Reproducability

Start forge server
See error

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

https://gist.github.com/viminio/c677cba9f31dcf7086c1a098309bcaa3

**Comment by someaddons** [comment]
its warning you about a mod adding unnamed loottables, report it to that mod instead.
