### ISSUE TITLE
[Bug]: force loading chunks with Open Parties and Claims does not work

### ISSUE THREAD

**Issue by JakeHumphries4** [someaddons/performant_issues#257]
### Describe the bug you're experiencing

Chunks marked for force loading are not loaded as intended when the player is not near.
I have tested this on both client and server by placing crops in a chunk both in the nether and ~10000 blocks away in the overworld in a force loaded chunk. When stating at spawn, waiting a minute or so, and setting the randomTickSpeed to 1000, the crops so no progress in their growth. This is not true for a client/server that doesn't contain the performant mod. 

### Reproducability

Install both performant 1.18.2 and Open Parties and Claims for the same version. Any claim that is marked as force loadable will not be force loaded as required. 

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

https://gist.github.com/JakeHumphries4/521fab95da27a51a13ff72f133c3652a

**Comment by JakeHumphries4** [comment]
any update on this?

**Comment by XionioXMaster** [comment]
same!
