### ISSUE TITLE
[Bug]: Create mod: moving blocks disappear and deatch + other issues

### ISSUE THREAD

**Issue by Momfie** [someaddons/performant_issues#258]
### Describe the bug you're experiencing

Mechanical Piston (+Sticky) | Bearing (windmill, mechanical, Clockwork) | items get stuck or disappear from 1 Conveyor Belt to the Next | Cart Assembler | Gantry Carrage/Shaft |

listed blocks have issues, may be more

### Reproducability

use any of these blocks

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

-no log

**Comment by someaddons** [comment]
sounds like the entities just are hidden, try setting the `enableDynamicEntityRendering` config to false
