### ISSUE TITLE
[Bug]: Entity crash with performant

### ISSUE THREAD

**Issue by ReedJr** [someaddons/performant_issues#260]
### Describe the bug you're experiencing

When an certain entity kills a player the sever/world crashes.

### Reproducability

Every time a goblin trader kills a player the crash happens. 

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

https://gist.github.com/ReedJr/7205c370fd6c43ede3fca5a4af0cb9f5

**Comment by someaddons** [comment]
problem of the goblin traders mod
