### ISSUE TITLE
[Bug]: Performant causes  crash.

### ISSUE THREAD

**Issue by Delseyrian** [someaddons/performant_issues#265]
### Describe the bug you're experiencing

Server keeps crashing after an hour due to this error, not sure what I'm doing wrong, any idea?

### Reproducability

No clue, still can't figure out what's causing this on my server.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

https://gist.github.com/Delseyrian/5e4ad5e793ba42459db9b3bc866df5a6

**Comment by someaddons** [comment]
that is not the cause of the crash, just the last log messages due to performants threads getting shut down
