### ISSUE TITLE
[Bug]: Damage tilt occurs when "over healing"

### ISSUE THREAD

**Issue by BrokedArrer** [someaddons/performant_issues#266]
### Describe the bug you're experiencing

I added Performant to my server and if a player has more then 20 health (Full hearts), and you have a mod installed that allows over max health of 20, if you heal or "over heal" it bugs out the health bar GUI and you get a damage tilt, every time you tick a regen. I have tried removing, and restarting server and it goes away. As soon as I reinstall it begins again.

### Reproducability

Do not have performant installed, install Lost Trinkets, give yourself Heart shards to go over max health. Have Appleskin or any other health overlay mod installed with Lost Trinkets. Login, and give yourself all heart shards, putting you at 24+ max health. Logout, install Performant, restart server and log back in. Inflict damage any way, eat food to saturate yourself and begin regen'ing, after your health hits "max" you will take damage hits that inflict no damage as you "over heal"

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

No log was given.

**Comment by someaddons** [comment]
fixed on 4.0m

**Comment by BrokedArrer** [comment]
Thats amazing! I have it installed on my server and it works perfectly, however its almost completely stopping hostiles from spawning, how can I disable it from messing with any and all spawn rates?

**Comment by someaddons** [comment]
set in the config `spawnInterval` to 1, or disable `fastChunkBlocks` in the config
