### ISSUE TITLE
java.lang.NullPointerException: null at net.minecraft.pathfinding.PathHeap.func

### ISSUE THREAD

**Issue by SonicSpeedster16** [someaddons/performant_issues#27]
**Describe the bug**
No noticeable problems or crashes, just an error I noticed in the server log.

**To Reproduce**
1. Unknown (multiple players were playing on the server at the time the error was displayed in the log.

** Mod version **
Minecraft 1.15.2
Forge 31.2.43
Performant 3.11m
Modpack: https://www.curseforge.com/minecraft/modpacks/the-new-adventure/files/3068481

** Logs **
https://gist.github.com/SonicSpeedster16/0ab6cc71f56c01c5e19bea3a04e173c9

**Comment by someaddons** [comment]
should be fixed in v3.12m
