### ISSUE TITLE
[Bug]: ban item plugin

### ISSUE THREAD

**Issue by Eug3nK** [someaddons/performant_issues#270]
### Describe the bug you're experiencing

I use mohist to be able to use mods and plugins at the same time. But I want to use a plugin to be able to ban certain items so that they cannot be crafted or used. the plugin works correctly, but after I add the performance mode on the server, the plugin lets the players continue to craft those banned itms. Do you think you can solve this?

### Reproducability

install the plugin and the performance module. give /banitem "item" craft
after you've banned him, you take out your op and try to craft that itm, the first time it doesn't let you, but if you hit it several times, it lets you craft it

plugins: https://www.spigotmc.org/resources/banitem-1-7-1-19.67701/

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

idk

**Comment by someaddons** [comment]
mohist is not supported
