### ISSUE TITLE
[Bug]: invisible chunks on forge 1.19.2 (patreon version)

### ISSUE THREAD

**Issue by SniffSniff125** [someaddons/performant_issues#271]
### Describe the bug you're experiencing

all looked normal at first, but after some travelling, all chunks in front of me were invisible.
they where still there, i could interact and walk, but i count not see any item nor block nor entity.
i tried to reload texture packs, reload all chunks but nothing worked. so i had to rejoin to world
(and it is a problem because it happens often)

the version is 1.19.2 (i found it on patreon but i can't select it on the report)

### Reproducability

- load the a world with performant installed (or create a new one)
- travel for a while (in the nether the bug seems to happen more often)
- the chunks should be invisible as if walking in the void

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

https://gist.github.com/SniffSniff125/7628be01f422fce184178f1bbc5323e9

**Comment by someaddons** [comment]
hey, performant does not touch chunk rendering and I havent run into those issues myself on 1.19.2 either so its either some incompat with another mod, or one of your rendering mods is causing the problem. Not seeing any errors in the log indicating which though
