### ISSUE TITLE
[Bug]: Performant causing crash due to mixins conflict with another mod 

### ISSUE THREAD

**Issue by StormCircuit** [someaddons/performant_issues#272]
### Describe the bug you're experiencing

With my modset, I have found that using performant with it causes an error from some sort of fall velocity mixin being missing that another mod needs. This causes a fatal error which forces the server to close.

I added the modpack manifest.html contenst to the gist below. It has a list of all mods.

Latest version of FML for 1.19.2 and all mods.

This is on 1.19.2 by the way. The issue tracker does not support 1.19 though.

### Reproducability

Load the server with this set of mods. Install/uninstall performant to observe crash appear/disappear respectively.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Forge

### Logs

https://gist.github.com/StormCircuit/c085ff2c15491bc1d081cf6132cb7789

**Comment by someaddons** [comment]
fixed in 9.2
