### ISSUE TITLE
[Bug]: Shield blocking animation not visible for other players

### ISSUE THREAD

**Issue by zzzaitegui** [someaddons/performant_issues#273]
### Describe the bug you're experiencing

If you play on multiplayer and block with any shield, vanilla or otherwise, for other players your shield appears unchanged as if you weren't blocking, it makes axe and shield PvP really difficult as you can't know if they are blocking or not. 

This happened with Performant 9.0 for forge 1.19.2 version 43.2.10 in particular. First noticed on PvP Legacy.

I had to mark this issue as 1.18.1 because there's no option for the 1.19.2 version. 

### Reproducability

Enter any 1.19.2 forge server and have someone block with their shield, you will not see them blocking and if you hit them with an axe you will hear the shield disabled sound but viasually nothing will change.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

no_log_required

**Comment by someaddons** [comment]
fixed in 9.2
