### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Asaurus64** [someaddons/performant_issues#275]
### Describe the bug you're experiencing

having performant mod and spawning first in a world causes the game to crush, reason being a single tick of the internal server took 180,01 seconds and maximum should be 0,05 seconds.
the crushing is caused by the mods adaptive performance tweaks and modernfix
https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks
https://www.curseforge.com/minecraft/mc-mods/modernfix
here is the crash report and log

[crash-2023-06-27_23.25.44-server.txt](https://github.com/someaddons/performant_issues/files/11887499/crash-2023-06-27_23.25.44-server.txt)
[crash-2023-06-27_23.38.17-server.txt](https://github.com/someaddons/performant_issues/files/11887557/crash-2023-06-27_23.38.17-server.txt)

[2023-06-27-1.log.gz](https://github.com/someaddons/performant_issues/files/11887504/2023-06-27-1.log.gz)
[2023-06-27-1.log.gz](https://github.com/someaddons/performant_issues/files/11887559/2023-06-27-1.log.gz)

### Reproducability

put mods on and generate a world

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

[2023-06-27-1.log.gz](https://github.com/someaddons/performant_issues/files/11887504/2023-06-27-1.log.gz)

**Comment by someaddons** [comment]
not a performant issue
