### ISSUE TITLE
[Bug]: Server crashing on start

### ISSUE THREAD

**Issue by Darkwolf202** [someaddons/performant_issues#277]
### Describe the bug you're experiencing

I'm unable to start my server.
Removing Performat allows the server to boot normally

Modlist:

[debug.log](https://github.com/someaddons/performant_issues/files/11891196/debug.log)

### Reproducability

Start the server

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Forge

### Logs

https://gist.github.com/Darkwolf202/6db18b746fe1b69096f6c1c4ea17f265

**Comment by someaddons** [comment]
incompatibility with origins, they should be using an attribute modifier instead of a mixin

**Comment by someaddons** [comment]
fixed in the newest
