### ISSUE TITLE
[1.16.1 - 3.12m] Ticking entity crash on client

### ISSUE THREAD

**Issue by sapientem** [someaddons/performant_issues#28]
**Describe the bug**
A forge 1.16.1 server running the Enigmatica 6 modpack is crashing on the client only when multiple entities are dropped in close proximity to each other. Doesn't matter what entity and it happens almost immediately.

**To Reproduce**
1. Load Enigmatica 6 modpack on a server with Performant 3.12m installed on both client and server.
2. Join server and break blocks in rapid enough succession to get them to "clump" up before picking them up.
3. Client crashes, server is fine.

**Expected behavior**
No crash?

**Mod version**
performant-1.16.1-3.12m

**Logs**
https://gist.github.com/sapientem/2d6cf22b5edb7d6c39315f0fa2f677d9

**Comment by sapientem** [comment]
Some more curious results:

- Removing Performant on the client (keeping it on the server) introduces repeating messages: https://imgur.com/a/HwLLheH
- Eventually the client crashes with the error "Internal server error" (descriptive, huh?): https://imgur.com/0ZT8uTx
- Debug logs are identical to those screenshots and provide no additional insight.
- All issues are resolved by downgrading to 3.11m on the server.

**Comment by someaddons** [comment]
resolved in the newest :)
