### ISSUE TITLE
[1.16.2] Unable to start

### ISSUE THREAD

**Issue by ghost** [someaddons/performant_issues#280]
I'm unable to start my game.
Removing Performant allows the game to start normally

**Mod list:** https://gist.github.com/SebitaaS3/366193854a8ceef09bbbec81cd59f86d

**Modloader Version:** 1.16.2-Forge-33.0.61

**Logs:** https://gist.github.com/SebitaaS3/470654c4fbc495e3e2d0924c36cbf7b1

**Comment by someaddons** [comment]
1.16.2 is not supported anymore
