### ISSUE TITLE
[Bug]: performant-1.19.2-10.0 incompatible with your other mod cupboard-1.19.2-1.8

### ISSUE THREAD

**Issue by Minebrah** [someaddons/performant_issues#282]
### Describe the bug you're experiencing

When running both mods and starting a game, it stays locked at the loading screen at 0%

### Reproducability

Add both mods to mod folder and launch game.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Forge

### Logs

https://gist.github.com/Minebrah/c3c472e8ebf2aa843b9e70cb57ee03d0

**Comment by someaddons** [comment]
fixed in 10.2
