### ISSUE TITLE
[Bug] Phosphophyllite incompatibility

### ISSUE THREAD

**Issue by heavytfc** [someaddons/performant_issues#283]
### Describe the bug you're experiencing

minecraft says Phosphophyllite is incompatible with Performant 
Edit: Phosphophyllite is a library mod (of which I do not believe even has any conflicting files or edits to files) for two mods, these two dependent mods aren't being called incompatible just Phosphophyllite

### Reproducability

install Performant and Phosphophyllite and launch

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

C:\Users\redry\curseforge\minecraft\Instances\custom 1\logs

**Comment by someaddons** [comment]
it is Phosphophyllite choosing to declare itself as incompatible despite not actually being
