### ISSUE TITLE
[Bug]: Crash when entering a world using Performant and Connectivity at the same time

### ISSUE THREAD

**Issue by MarijnIsN00B** [someaddons/performant_issues#285]
### Describe the bug you're experiencing

My game crashes every time I enter a world using Performant and Connectivity at the same time

### Reproducability

Install Performant and Connectivity, enter a world, crash.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

https://gist.github.com/MarijnIsN00B/066fe8bfd6c3fc44ff92605fc766f156

**Comment by someaddons** [comment]
randompatches is crashing, read the compat section of connectivity: https://www.curseforge.com/minecraft/mc-mods/connectivity
