### ISSUE TITLE
Crash timeout

### ISSUE THREAD

**Issue by MarijnIsN00B** [someaddons/performant_issues#286]
### Describe the bug you're experiencing

Game sometimes crashes randomly, might be an incompatibility with enhanced celestials but since I cant figure out how to reproduce it properly.

### Reproducability

Like I said, I cant figure out how to reproduce it properly.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

https://gist.github.com/MarijnIsN00B/273ad21a190f517058f259b261e8f802

**Comment by someaddons** [comment]
looks like zombie awareness keeps loading chunks and times out the server
