### ISSUE TITLE
Please do not overwrite any method!!!

### ISSUE THREAD

**Issue by Ecdcaeb** [someaddons/performant_issues#287]
### Describe the bug you're experiencing

Post at MinecraftForge discord:
https://discord.com/channels/1129059589325852724/1137624560221569046/threads/1199965256135483432
```text
LgNgVu

I installed more mods into minecraft forge and it did the same thing and couldn't play the game
Logs:https://drive.google.com/file/d/17ufVo6qXH9mEMW7rC1mLicNGPzGqaU8W/view?usp=sharing
![image](https://github.com/someaddons/performant_issues/assets/107909747/03307c0d-d149-4e40-bf68-9afb9d9c5ac5)
```

### Reproducability

install `performant` and `vice.does_it_tick`

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

https://drive.google.com/file/d/17ufVo6qXH9mEMW7rC1mLicNGPzGqaU8W/view?usp=sharing

**Comment by someaddons** [comment]
Does it tick is not going to be supported, they simply copied code from various mods, including performant into their own.

**Comment by Deepfriedyag** [comment]
> Does it tick is not going to be supported, they simply copied code from various mods, including performant into their own.

Is this true for the "DoesPotatoTick?" mod as well? Does Performant do everything that mod does?
