### ISSUE TITLE
[1.12.2] - Latest Version 1.11.jar is an empty jar file

### ISSUE THREAD

**Issue by bwiggin10** [someaddons/performant_issues#288]
### Describe the bug you're experiencing

Decompiling the jar files reveals that the mod only creates a config file and does nothing else.

### Reproducability

Decompiling the jar files reveals that the mod only creates a config file and does nothing else.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

N/A

**Comment by someaddons** [comment]
1.12.2 isnt supported anymore

**Comment by bwiggin10** [comment]
??? So instead of leaving the prior version or informing people, you upload a blank Jar? Reported on Curseforge.

**Comment by skystorage** [comment]
Uploading blank jar instead of informing people? LOL

**Comment by ACGaming** [comment]
> Who do you think you are?  
> Runnin' 'round leaving scars  
> Releasing an empty jar  
> Tearing love apart

**Comment by SticksS123** [comment]
I can't beleive this shit is still up on curseforge lmao
