### ISSUE TITLE
[Bug]: [1.20.1] Crash with Create Mod

### ISSUE THREAD

**Issue by RedBeast1959** [someaddons/performant_issues#289]
### Describe the bug you're experiencing

Forge 47.2.20
performant-1.20.1-11.9
create-1.20.1-0.5.1.f

I lost discord connection, so I report here.
Btw, this bug actually happend in 1.19.2 version of perfomant and I reported in your discord. And you fixed it.
But unfortunately, this bug revive from its grave in latest performant.

### Reproducability

1. Open creative mode tab or JEI
2. Find Empty Blaze Burner
3. Hold W to play demonstration video.
4. Minecraft died of heart attack

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.3

### Modloader version

Forge

### Logs

https://gist.github.com/RedBeast1959/9e028a619cde0ccc970cd11936921484

**Comment by someaddons** [comment]
fixed in newest
