### ISSUE TITLE
[1.15.2] Nature's Aura Incompatability

### ISSUE THREAD

**Issue by HockeyZman2000** [someaddons/performant_issues#29]
As the title says, when Performant and Nature's Aura are combined together (just tested) the mod becomes unplayable. One of the first steps in the mod involves an oak sapling centered in the middle of a ritual circle (called Ritual of The Forest). The tree gets consumed and new items are made from it. This works perfectly until Performant is installed alongside it, which prevents the sapling from being grown by any means inside the ritual. I also sometimes experience crashes when the sapling tries to grow. I'm not entirely sure how or what or why Performant deals with tree saplings but it's blocking progression. A fix or at least a config option to turn the sapling features off would be greatly appreciated.

**Comment by someaddons** [comment]
performant doesnt have any sapling modifications so not sure why that would be affected

**Comment by HockeyZman2000** [comment]
(https://youtu.be/0E-sc5tbvr4)

I've recorded a brief, untrimmed video showing what is supposed to happen vs what actually is happening with both installed. The video description has more information to help. Sorry for all the trouble but I would just really like to see this get fixed because I love the optimizations this mod provides.

**Comment by someaddons** [comment]
fixed in v3.12m

**Comment by HockeyZman2000** [comment]
Thanks!
