### ISSUE TITLE
[Bug]: Crash with Ice and Fire mod

### ISSUE THREAD

**Issue by njockfatmih** [someaddons/performant_issues#291]
### Describe the bug you're experiencing

I was flying around the world and the server crashed, the log shows that it was because of "Cockatrice". 

### Reproducability

spawn Cockatrice

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Forge

### Logs

https://gist.github.com/njockfatmih/ffa7ffcb28dca8f9b09619c32b380456

**Comment by someaddons** [comment]
is fixed in the newest
