### ISSUE TITLE
Question: Performant 1.20.1 incompatibilities

### ISSUE THREAD

**Issue by Astra901** [someaddons/performant_issues#294]
### Describe the bug you're experiencing

Hello, I currently run a server running the all the mods 9 no frills pack, and we are running into some performance issues on the server end. In order to download this mod or seemingly contact you in any way, I need to pay you 5$ on patreon, which I'll be happy to do if I can be guaranteed the mod is compatible.. but this is literally the only way I could find to ask.

### Reproducability

Be interested in performant 1.20.1

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.3

### Modloader version

Forge

### Logs

https://gist.github.com/Astra901/2aae76515458c27bb3dea2f5ca062d03

**Comment by tajemniktv** [comment]
Hey, I actually DMed Sam about the same thing today:P
I hope they don't mind me sharing this, but that's cut from a message they sent me:)

> the incompatiblities I'm aware off are other performance mods as lithium(and its forge ports), vmp, servercore. A bunch of my patreons use it on ATM packs

After talking with them, I decided to support their work on Patreon, so if any issues arise, I'll report them in this repo. I guess testing for yourself is the best way, haha
