### ISSUE TITLE
Concurrent Operation Exception on player teleport

### ISSUE THREAD

**Issue by GradiusLover2000** [someaddons/performant_issues#31]
**Describe the bug**
If the player teleports, there is a high chance Concurrent Operation Exception will be thrown when the world is updating its lighting.

**To Reproduce**
1. Download waystones mod and install alongside (to make teleporting easiest)
2. teleport around with a couple waystones.  high chance of crash although it doesn't always happen

** Mod version **
Performant 1.10-MC 1.12.2
happens server side, client is irrelevant.

** Logs **
[crash-2020-10-26_02.04.58-server.txt](https://github.com/someaddons/performant_issues/files/5436456/crash-2020-10-26_02.04.58-server.txt)

**Comment by someaddons** [comment]
1.12 is no longer supported

**Comment by GradiusLover2000** [comment]
It was phosphor colliding with your mod anyway.  so I ditched phosphor and the issue was fixed without performance loss.  no problem.
