### ISSUE TITLE
[1.16.4]Crash in startup

### ISSUE THREAD

**Issue by MarinaMarissa** [someaddons/performant_issues#34]
**Describe the bug**
Game crashes

**To Reproduce**

**Expected behavior**

**Screenshots**

** Mod version **
3.12m
other mods:
5zigHUD.jar
AI-Improvements-1.16.2-0.3.0.jar
AmbientSounds_v3.0.21_mc1.16.2.jar
AppleSkin-mc1.16.2-forge-1.0.14.jar
BetterPvP_20.27.2.1_Forge_1.16.4.jar
Bookshelf-1.16.4-9.0.2.jar
cloth-config-forge-4.1.0.jar
CustomSkinLoader_Forge-14.13-SNAPSHOT-199.jar
CustomWindowTitle-1.15+v1.1.0.jar
durabilityviewer-1.16.4-forge35.0.7-1.9.jar
FastFurnace-1.16.3-4.3.0.jar
FastWorkbench-1.16.3-4.4.0.jar
forgeautofish-1.0.5-1.16.3.jar
FpsReducer-mc1.16.4-1.18.jar
Hwyla-forge-1.10.11-B78_1.16.2.jar
inventoryprofiles-forge-1.16.2-0.4.2.jar
jei-1.16.4-7.6.0.55.jar
jeiintegration_1.16.3-6.0.0.8.jar
lanserverproperties-1.4.jar
light-overlay-5.5.4.jar
MineMenu-1.16.2-1.8.6.jar
OptiFine_1.16.4_HD_U_G5.jar
OptiForge-MC1.16.4-0.4.1.jar
performant-1.15-3.12m.jar
Placebo-1.16.3-4.3.3.jar
randompatches-1.16.2-1.22.1.2.jar
WorldEdit-CUI-FE3-1.16.4-3.0.8.jar
worldedit-forge-mc1.16.3-7.2.0-dist.jar
XaerosWorldMap_1.11.0.1_Forge_1.16.4.jar

** Logs **
[latest1.log](https://github.com/someaddons/performant_issues/files/5531119/latest1.log)

**Comment by someaddons** [comment]
You're trying to run the 1.15 version on 1.16, ofc this does not work.
