### ISSUE TITLE
[1.15.2] Сompatibility with spiders 2.0 mod

### ISSUE THREAD

**Issue by FuryOfFools** [someaddons/performant_issues#35]
**Describe the bug**
The mod makes it so that the spiders begin to crawl along the walls and ceilings, but with the performant they seem to have forgotten how to crawl along the walls. 

**To Reproduce**
1. install [Spiders 2.0](https://www.curseforge.com/minecraft/mc-mods/spiders-2-0) mod
2. build a small wall
3. summon spiders in the hope that they will climb the wall to attack you
4. but they don't

**Expected behavior**
Spiders crawl on walls and ceilings as if it were an ordinary floor

**Screenshots**
example wrong behavior: 
![image](https://user-images.githubusercontent.com/40697349/99131834-9a5b7180-262d-11eb-9705-86a0d60c61c8.png)
right behavior (without performant in this case): 
 ![image](https://user-images.githubusercontent.com/40697349/99131874-c119a800-262d-11eb-8b10-54d8c65fbfa7.png)

** Mod version **
performant 3.12m
spiders 2.0 v1.0.4

** Logs **
[latest.log](https://github.com/someaddons/performant_issues/files/5539828/latest.log)

**Comment by someaddons** [comment]
checked the mod and its likely not possible to do this, sorry

**Comment by FuryOfFools** [comment]
Why it is not possible?
