### ISSUE TITLE
[1.15]Crash when ticking entity

### ISSUE THREAD

**Issue by sandtechnology** [someaddons/performant_issues#37]
**Describe the bug**
Crash when ticking entity

**To Reproduce**
Unknown

**Expected behavior**
No error

**Screenshots**
None

** Mod version **
performant-1.15-3.12m

** Logs **
Latest/Crash log:https://paste.ubuntu.com/p/jRhfb4bGWG/

**Comment by someaddons** [comment]
3.13 is out and fixes this xD next time check for an update
