### ISSUE TITLE
[1.15.2]Ticking entity causing crashes

### ISSUE THREAD

**Issue by Wi1c** [someaddons/performant_issues#40]
**Describe the bug**
Minecraft salmon pathing causing a ticking entity error on server.

**To Reproduce**
unknown

**Expected behavior**
Not crashing

**Screenshots**
NA

** Mod version **
1.15-3.13m

** Logs **
https://pastebin.com/qLCqzeaz

**Comment by someaddons** [comment]
turn on fastPathFind in the configs
