### ISSUE TITLE
spider crash with tripwire?

### ISSUE THREAD

**Issue by mahjerion** [someaddons/performant_issues#41]
**Describe the bug**
Honestly I don't know, I just have the crash reports as the server admin. The crash has happened a few times though and seems to be exclusive to spiders and trip wire?

**To Reproduce**
1. Sorry I can't provide much info but judging from the report probably a spider walks into a trip wire or something.

**Expected behavior**
No crash.

**Screenshots**
N/A

** Mod version **
3.13m

** Logs **
Latest/Crash log
https://gist.github.com/mahjerion/712027172ec471c0129350ded1d4ef82

**Comment by someaddons** [comment]
crash report was enough, fixed in 3.14m :D

**Comment by mahjerion** [comment]
You're the best <3
