### ISSUE TITLE
[1.12.2] Crashes on startup with Mixinbootstrap(Bruh)

### ISSUE THREAD

**Issue by JustHelpingOut** [someaddons/performant_issues#42]
When starting up 1.12.2, with only it and MixinBootstrap-1.0.5(Required dependency, unrequire it noob)
Download it and mixinbootstrap
Launch game
Crash report - Error Code 0 (There is none)

Please unrequire MixinBootstrap for version 1.12.2 - 1.10

This may or may not be a problem with Curseforge migrating. Good luck on fixing it, whatever the problem could be.

Log:
[latest.log](https://github.com/someaddons/performant_issues/files/5631163/latest.log)

**Comment by BugmanBugman** [comment]
You're not supposed to have mixin bootstrap on 1.12.2

**Comment by someaddons** [comment]
^^ what he says above and 1.12 is no longer supported anyways. Also what kinda of behaviour is this? Learn some manners.
