### ISSUE TITLE
[1.15.2] Dyeable blocks cause crash at launch

### ISSUE THREAD

**Issue by Late-Night** [someaddons/performant_issues#43]
any mod that adds dyeable blocks causes a crash during loading

**To Reproduce**

1. add cooking for blockheads and performant to your mods folder
2.  attempt to launch the game

**Expected behavior**
i expected no issue

** Mod version **
performant: 3.13m
CFB: 8.0.3

crashlog:

https://gist.github.com/Late-Night/27e3f714f745aec657c1679506d2a9d5#file-crash-2020-11-21_10-49-23-client-txt

**Comment by someaddons** [comment]
performant is not even installed when that crash happened, so closing this
