### ISSUE TITLE
[Request] upload source code of 1.12 version of Performant to let users fix issues

### ISSUE THREAD

**Issue by gatoborrachon** [someaddons/performant_issues#44]
I have an issue with Sync, and i know you don't want to work with 1.12 anymore, so I kindly come to ask if you can consider to open source the code of the 1.12 version of Performant, and no problem if you don't want.

**Comment by someaddons** [comment]
the 1.12 version is very shallow and is lacking about 99% of the features current performant has, there is barly any reason to use it at all, nor does it really make sense to develop on it.
