### ISSUE TITLE
Entity Collision Thread Crashing

### ISSUE THREAD

**Issue by sirati97** [someaddons/performant_issues#45]
**Description**
We are using Valhelsia 2 latest version, a modpack for 1.15. When using our XP farm all items and xp in that chunk become uncollectable, entity collisions stop. During that time performant throws an exception. 

**To Reproduce**
1. place an apotheosis spawner
2. right click with blaze spawn egg, netherstar, chorus fruit, comparator, 64 sugar, 64 clocks
3. use redstone to provide 20 seconds active redstone signal (spawn for 20 seconds)
4. exception is thrown and bug happens

The problem is reproducible on our server. I can provide the chunk with the mob farm if needed or provide access to the server. 

**Expected behavior**
Not having the thread performing entity collisions crash. Drops and items should be collectable

**Mod version**
1.15-3.12m 

**Crashlog**
https://gist.github.com/sirati97/df9b5af6d0921733d8207c7a75fb9c06

**Comment by someaddons** [comment]
update^^

**Comment by sirati97** [comment]
Hello,
i would like to reopen this issue. Updating did fix the issue of the exception being thrown in the console. However it does not seem to appear to have fixed the issue of not being able to pickup items. Also it appears that other entities behave abnormally in affected chunks. For example botania mana spreader cease to function.

Based on that the exception is fixed now, I dont have any idea what would be causing the bug.
Cheers
