### ISSUE TITLE
Performant makes create pulse repeater unrealiable

### ISSUE THREAD

**Issue by Paspartout** [someaddons/performant_issues#46]
When using preformant together with the create mod it seems to make the pulse repeater unrealiable.
Since the pulse repeater is inheriting from `net.minecraft.block.RedstoneDiodeBlock` and is using [scheduledTick](https://github.com/Creators-of-Create/Create/blob/32b0a01c3ad02db1f94d17e6d00e6c9adde8acd5/src/main/java/com/simibubi/create/content/logistics/block/diodes/PulseRepeaterBlock.java#L37) I think some of the load balancing or optimization performant does breaks it. I'm a bit sad the mod isn't opensource. Would have loved to try fixing it myself.
Thanks for improving the performance of forge 1.16 though, it's really needed and appreciated.

I already tired disabling TE balancing but it didn't help since I think it's not really a tile entity in that case.

**To Reproduce**
1. Install create for minecraft 1.16 together with the performant mod.
2. Place down a pulse repeater  and connect it to lever.
3. Flick the lever several times
4. The output will only pulse some of the times. It's not reliable anymore.

**Expected behavior**
The pulse repeater should work 100% of the time.

** Mod version **
performant-1.16.2-4-3.24m.jar
create-mc1.16.3_v0.3a.jar

**Video of the issue**

https://user-images.githubusercontent.com/2720369/103097835-e6c0a680-4608-11eb-8882-f523d10962f8.mp4

**Comment by SamL2020** [comment]
Same issue with create-mc1.16.3_v0.3b

**Comment by someaddons** [comment]
ye this is a visual thing, where it doesnt update the client side that frequently. Affected by the fastChunkBlocks config setting.
Funnily the repeater actually repeat the signal 100% in vanilla either

**Comment by someaddons** [comment]
oh btw loadbalancing is only a throttling mechanic which does sth when the server is over the configured lagging threshold, before nothing ever gets throttled. By default thats 55ms ticks which is like 19 TPS

**Comment by Paspartout** [comment]
Setting `fastChunkBlocks = false` ineed fixes the problem. It seems to working 100% reliable now but I only tried like 25 switches.

**Comment by someaddons** [comment]
ye its just a matter of sending updates, the redstone signal still exists/takes effect

**Comment by someaddons** [comment]
should be fixed in v3.25m
