### ISSUE TITLE
Crash on server startup on DW20 1.16 with performant installed on server

### ISSUE THREAD

**Issue by ImVaskel** [someaddons/performant_issues#47]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**

After adding performant-1.16.2-4-3.24m.jar to DW20 1.16 version 1.1.1, the server crashes on boot.

**To Reproduce**

Start server with performant installed, it crashes.

**Expected behavior**
I expected the server to boot

**Screenshots**

N\A

** Mod version **
Your mods version

performant-1.16.2-4-3.24m.jar

** Logs **
Latest/Crash log

CRASH LOG - https://static.moddedminecraft.club/paste-picturized-grecianized-somnambulism-Fairwater.txt

**Comment by someaddons** [comment]
disable fastChunkBlocks in the config for now to prevent it

**Comment by someaddons** [comment]
should be fixed in v3.25m

**Comment by DreiPixel** [comment]
had the same problem and updated perfomant but now server wont start.
this is the last stuff the server says before crashing (no crash log is being generated for some reason)

https://paste.ee/p/7yuyt
