### ISSUE TITLE
[1.16.4] fasterHoppers causing hoppers not to intake items

### ISSUE THREAD

**Issue by rckymtnrfc** [someaddons/performant_issues#48]
Items are not being pulled into hoppers, They just float on top.

**To Reproduce**
1. Go to hopper
2. Drop item on it
3. See item not getting pulled in
4. Profit!

**Expected behavior**
Obviously the item should pull into the hopper.  I double checked that there was no redstone signal effecting the hopper.  Once I turned off fasterHoppers in the config, hoppers started working as expected.

** Mod version **
forge-1.16.4-35.1.12
performant-1.16.2-4-3.24m

** Logs **
https://pastebin.com/KDyfQVyT

**Comment by someaddons** [comment]
should be fixed in v3.25m
