### ISSUE TITLE
Don't use @Overwrite on CompoundNBT#equals

### ISSUE THREAD

**Issue by TheRandomLabs** [someaddons/performant_issues#49]
Performant uses an `@Overwrite` on `CompoundNBT#equals`, meaning RandomPatches' `@Redirect` causes a crash (TheRandomLabs/RandomPatches#150). 

**To Reproduce**
Install the [alpha build](https://www.curseforge.com/minecraft/mc-mods/randompatches/files/3148667) of RandomPatches and Performant.

**Expected behavior**
No crash.

**Mod version**
RandomPatches 2.0.0
Performant 1.16.2-4-3.24m

**Logs**
https://gist.github.com/WenXin20/499ded8b508d2062dd2f08c28949bbd9

Hopefully, whatever patch you're applying can be done with an `@Inject`. If not, I'll simply disable my patch when yours is enabled. Thanks!😄

**Comment by someaddons** [comment]
ye I've found a way to make it with injects, basically I modify the logic around but not the actual comparison call like you do

**Comment by someaddons** [comment]
should be fixed in v3.25m

**Comment by TheRandomLabs** [comment]
Thank you!
