### ISSUE TITLE
Mixin Crash w/ Optifine

### ISSUE THREAD

**Issue by WenXin20** [someaddons/performant_issues#51]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
- After updating, the mod now crashes with Optifine.

**To Reproduce**
1. Install Optifine
2. Launch game
3. Crash

**Expected behavior**
- No crashes

** Mod version **
`Performant v3.25m
`

** Logs **
[Latest/Crash log](https://gist.github.com/WenXin20/a3c408d3d26a66c13313a1e182a4f44a)

**Comment by someaddons** [comment]
I can start perfectly fine with optifine

**Comment by WenXin20** [comment]
Strange. It's definitely crashing for me with Optifine and performant. And the previous version of performant does not crash with Optifine.

**Comment by Gbergz** [comment]
Newest version also crashes when used on a server.

**Comment by someaddons** [comment]
gonna need full logs on this

**Comment by WenXin20** [comment]
The link above is the full log. That is all that was printed before it crashed.

**Comment by WenXin20** [comment]
But I think I got it working again by reopening the minecraft launcher. It might've been a bug with the launcher? I don't really remember how I got it to work unfortunately.

**Comment by CMYKMatter** [comment]
Actually I can confirm this one as well. Same problem in that versions 3.25 and 3.26 crash when loaded with Optifine. You can find my full log here: [Performant Log](https://pastebin.com/MTBW0ELi)

Rolling back to version 3.24 from December 24th fixes the issue and allows the mods to load properly.

**Comment by kingOf0** [comment]
removed **MixinBootstrap-1.0.5.jar**
removed **"minVersion": "0.6",** from **performant_mixin.json** from **performant.jar**
