### ISSUE TITLE
Game crashes with RandomPatches

### ISSUE THREAD

**Issue by rapphy243** [someaddons/performant_issues#52]
**Describe the bug. 1.12 is no longer supported, do not make bug reports for it.**
The game crashes with RandomPatches.

**To Reproduce**
1. Launch the game with RandomPatches
2. Game Crash

**Expected behavior**
The game launches normally.

** Mod version **
Performant 1.16.4 v3.25m
RandomPatches 1.16.4-1.22.1.11

** Logs **
[Latest.log](https://gist.github.com/rapphy243/ffc6fbb0fe1e2cceba6248cdce3d3335)

**Comment by rapphy243** [comment]
Whoops didn't use the alpha version of RandomPatches.

**Comment by doctor-something5000** [comment]
Update your java as well.
