### ISSUE TITLE
Spider 2.0 Compatibility

### ISSUE THREAD

**Issue by InteJason** [someaddons/performant_issues#53]
I see that someone has already made an issue: https://github.com/someaddons/performant_issues/issues?q=is%3Aissue+is%3Aclosed
But I wanna know is there an optional function I can disable in Performant to make it work?

Thanks for your time.

**Comment by someaddons** [comment]
to make what work?

**Comment by InteJason** [comment]
To make the spider 2.0 mod work while having performant installed, since it's not working properly currently

**Comment by DannyLeWasTaken** [comment]
Can confirm. Using 1.15.2 and I'm having issues with spider pathfinding. They're not able to climb up at all with Spider 2.0. and Performant installed.

**Comment by someaddons** [comment]
performant atm replaces the movement complety, which in turn causes your movement hooks to get lost, it probably would work if you'd change to override the move just as you did with the travel call for spiders

**Comment by Yourname942** [comment]
What happens if both  Spiders 2.0 and this is installed? (specifically 1.16.4)

**Comment by Camawama** [comment]
Can you please add a whitelist for mobs affected by Performant?

**Comment by BugmanBugman** [comment]
Any update on this?
