### ISSUE TITLE
Mixin Crashes on Startup

### ISSUE THREAD

**Issue by doctor-something5000** [someaddons/performant_issues#54]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
The game crashes showing a mixin crash when updated from v3.24m to v3.25m of Performant

**To Reproduce**
1. Download Performant v3.25m.
2. Start Minecraft from the launcher.
3. See error

**Expected behavior**
The game was expected to run flawlessly.

**Screenshots**
Unavailable

** Mod version **
performant-1.16.2-4-3.25m

** Logs **
[Latest/Crash log]
(https://pastebin.com/58Eu8nZ2)

**Comment by someaddons** [comment]
disable fastItemCompare or update randompatches to its 2.0 version, then it should no longer crash aswell

**Comment by doctor-something5000** [comment]
Oh thanks it works now!!! Didn't know it was a compatibility crash between those two. Thanks again
