### ISSUE TITLE
Please open source this mod

### ISSUE THREAD

**Issue by tofran** [someaddons/performant_issues#59]
Hello I'm having issues with this mod (in combination with others) but unfortunately I cannot debug it because the source code doesn't seem public.

I kindly request on behalf of the community if you could open source performant.

From my initial testing it actually has a benefit in a system with very low single core performance and high core count. This is a long living issue with Minecraft, thus everyone could benefit from this mod.

I think even you, the mod creator and this project would benefit a lot by involving the community in it. Otherwise it will never completely evolve to a mature solution.

Best regards

**Comment by someaddons** [comment]
I dont really want to run another community project, as this is for me more of a personal project I'm letting others use. Also there is barly any merit in having other devs look at it, as it'd require quite the understanding of vanilla code, my added code/adjustments and performance in general, it'd likely just cause much more time draining discussion compared to when I just do it myself right away.

**Comment by Daomephsta** [comment]
You don't have to run a community project. Other devs just want to be able to debug issues themselves. You don't have to go open-source either, visible source, or allowing decompilation would help others trying to debug.
Don't want PRs? Say so in the README, and direct anyone that misses that to said README.

**Comment by tofran** [comment]
> I dont really want to run another community project

> Don't want PRs? Say so in the README

You can actually restrict pull requests in the repo settings.


Having the source would allow everyone to know what exactly this mod does. Right now there are undocumented side effects and bugs. Having the source code available would allow for better debugging specially when dealing with incompatibilities.
As a one-person project, it is no possible to test and resolve all the issues with every possible mod, for everyone that opens an issue.

Obviously, everyone has their one opinion...

**Comment by quat1024** [comment]
Can you address this? https://web.archive.org/web/20200729141730/https://github.com/ldtteam/Performant/issues/48

I'm curious how Lithium could be stealing code from Performant, and not the other way around, when Lithium was... written first

**Comment by LordMZTE** [comment]
> Hello I'm having issues with this mod (in combination with others) but unfortunately I cannot debug it because the source code doesn't seem public.
> 
> I kindly request on behalf of the community if you could open source performant.
> 
> From my initial testing it actually has a benefit in a system with very low single core performance and high core count. This is a long living issue with Minecraft, thus everyone could benefit from this mod.
> 
> I think even you, the mod creator and this project would benefit a lot by involving the community in it. Otherwise it will never completely evolve to a mature solution.
> 
> Best regards

You can decompile the mod with a decompiler such as [jd-gui](https://java-decompiler.github.io/). This works well enough for debugging, although many symbols of the game will be remapped and thus not easily readable.
