### ISSUE TITLE
performant-1.16.2-4-3.25m.jar crashes to launcher/desktop during FMLs mod scanning process

### ISSUE THREAD

**Issue by Thombias** [someaddons/performant_issues#60]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
What the title says.

**To Reproduce**
1. Download performant-1.16.2-4-3.25m.jar
2. Start Minecraft
3. Bam! Almost instant crash

**Expected behavior**
performant-1.16.2-4-3.24m.jar loads and functions perfectly fine, but performant-1.16.2-4-3.25m.jar crashes right after FML has finished its early loading process (The part where it scans your entire mod folder before actually starting Minecraft)

**Screenshots**
No screenshot necessary

** Mod version **
performant-1.16.2-4-3.25m.jar

** Logs **
Latest/Crash log

**Comment by doctor-something5000** [comment]
Do you have random patches installed? If yes, then what version?

**Comment by Micaxs** [comment]
I assume its not compactible with `randompatches-1.16.4-1.22.1.11`
Seems to work fine with the beta version of `randompatches-1.16.4-2.0.1` 
So try and update your randompatches to their latest beta version to fix the issue.

**Comment by Thombias** [comment]
Sorry for the late response, last time i looked here i was already in bed. ^^
Yeah, i'm using RandomPatches, randompatches-1.16.4-1.22.1.11.jar in fact.

**Comment by someaddons** [comment]
nice :)
