### ISSUE TITLE
Wandering Trader can't remove his invisibility buff with fastCollisions = true

### ISSUE THREAD

**Issue by DerSchlingel01** [someaddons/performant_issues#61]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
Wandering Trader can't remove his invisibility buff with fastCollisions = true
He starts drinking milk, but it doesn't remove his invisibility buff and he keeps trying

**To Reproduce**
1. Start game with fastCollisions = true
2. Spawn Wandering Trader
3. /time set night
4. /time set day
5. Check him out

**Expected behavior**
He should be able to go visible again when the night is over.

**Screenshots**
/

**Mod version**
performant-1.16.2-4-3.25m and had the same issue with previous version.

**Logs**
/

**Comment by BugmanBugman** [comment]
Can confirm

**Comment by someaddons** [comment]
fixed in 3.26m
