### ISSUE TITLE
Incompatibility with Inspirations mod, milk cauldron glitches out

### ISSUE THREAD

**Issue by BugmanBugman** [someaddons/performant_issues#62]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
Title. Performant causes milk cauldron to bug out. Not sure which module of performant does it.
**To Reproduce**
1. go to cauldron
2. fill with milk
3. now right click
4. you can dupe buckets forever

**Expected behavior**
To not do whatever happened

**Screenshots**
https://streamable.com/
** Mod version **
3.25

please opensource :(

**Comment by BugmanBugman** [comment]
I reported it here to [them](https://github.com/KnightMiner/Inspirations/issues/194)

**Comment by DerSchlingel01** [comment]
Same issue here, but you can set cacheRecipes to false and it should work again.

**Comment by someaddons** [comment]
fixed in 3.26m was a recipe caching issue^^
