### ISSUE TITLE
Maybe a crash between Optifine and Performant? Not sure.

### ISSUE THREAD

**Issue by PossesiveGamer** [someaddons/performant_issues#63]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
I had optifine loaded before I installed this and when I started it up it kept crashing and I noticed this in the crash report. I have linked a pastebin of my full minecraft.log from the MultiMC console during loading because it didn't print a crash report. Also the version of Optifine I have installed. 

**To Reproduce**
1. Go to 'Launcher of choice'
2. Click on 'Launch'
3. Scroll down to 'After crash scroll down to red text and see performant'

**Expected behavior**
Load up and play the game.

**Screenshots**
![Error](https://user-images.githubusercontent.com/9295473/103182093-44a1f800-486e-11eb-9822-7893940dae30.PNG)

** Mod version **
performant-1.16.2-4-3.25m
OptiFine_1.16.4_HD_U_G5

<!--- IMPORTANT! You find logs in the /minecraft/logs/ folder. Please add your latest.log / (if it did crash)crash.log below with
** Logs **
Latest/Crash log
https://pastebin.com/1mxqz4zQ

**Comment by DerSchlingel01** [comment]
I got performant and optifine working, but I had a similar issue and had to update RandomPatches to 2.0.1 for my client/server to start.

**Comment by PossesiveGamer** [comment]
> I got performant and optifine working, but I had a similar issue and had to update RandomPatches to 2.0.1 for my client/server to start.

Ok I will try that and update.

**Comment by PossesiveGamer** [comment]
> > I got performant and optifine working, but I had a similar issue and had to update RandomPatches to 2.0.1 for my client/server to start.
> 
> Ok I will try that and update.
It has loaded so that has worked. Im sorry for posting an issue and it not related to the mod. This has been solved and will be closed.
