### ISSUE TITLE
Bug when using with Advent of Ascension (Nevermine) 1.15.2

### ISSUE THREAD

**Issue by Psychotrickser** [someaddons/performant_issues#66]
Performant's 'fastCollisions' isn't compatible with Advent of Ascension 3 (Nevermine). Combining those mods causes a bug:
Idk exactly why that happens but when you travel to another dimension the game thinks you're still in the overworld. When you walk around in the dimension what the server thinks you're doing is: you're going through solid walls in the overworld. So you continuously take damage until you die (suffocated in a wall) or until you leave the chunk the portal is in. I think that's when the server realises you're in another dimension and refreshes your position. 
The same happens when you go back to the overworld. 

There's a second bug where you become unable to collect stuff after travelling through the portal. Leaving and joining the server again fixes that. (I don't know how to reproduce that one atm)

1. Install Advent of Ascension 3.4.3 and Performant 3.14m for Minecraft 1.15.2
2. Enable 'fastCollisions' in the config file of Performant
3. Build a AoA (Advent of Ascension) portal somewhere in the underground
4. Go through the portal and walk around in the new dimension while staying inside the chunk the portal is in
5a. You keep taking damage until you die (suffocate in a wall) or leave the chunk. After leaving the chunk you can enter it again without having the bug occur
5b. Go back through the portal to the overworld and walk around without leaving the chunk the portal is in. You keep taking damage until you die or leave the chunk. After leaving the chunk you can enter it again without having the bug occur

Video of the bug: 
https://youtu.be/MV0znwAHNgM

long version with comments: https://youtu.be/fswhf-pisig

Mods version:
-Advent of Ascension 3.4.3
-Performant 3.14m
-Forge 31.2.47
Minecraft 1.15.2

**Comment by someaddons** [comment]
funnily I can't seem to reproduce this with performant and AoA

**Comment by Psychotrickser** [comment]
I've tried it multiple times with a clean 1.15.2 installation. The dimension Precasia is good for experiencing this bug. Are you keeping in mind that your dimension coordinates have to match overworld coordinates? Like in the video you suffocate in a wall when walking up to coordinates in the dimension at which there are blocks in the overworld at the exact same coordinates

**Comment by someaddons** [comment]
should be fixed in 3.15
