### ISSUE TITLE
[1.16.4] Crash with RandomPatches 1.22.1.11 exists.

### ISSUE THREAD

**Issue by ScottCTD** [someaddons/performant_issues#67]
**Crash with RandomPatches 1.22.1.11 exists.**

**To Reproduce**
1. Add Performant and RandomPatches
2. Launch and crash.

**Expected behavior**
Crash

**Screenshots**
Not Applicable

** Mod version **
performant-1.16.2-4-3.25m.jar

Latest Log: https://paste.ubuntu.com/p/DXkvMyz26Z/
Debug Log: https://paste.ubuntu.com/p/VKry8kg5QV/

**Comment by Tall-Bird** [comment]
I've gotten the same, with the same two mods.

I do have several more mods as well.

My log: https://pastebin.com/G72ZY8ub

**Comment by someaddons** [comment]
use performant 3.24 or update randompatches to 2.0
