### ISSUE TITLE
Cannot build underneath player while jumping

### ISSUE THREAD

**Issue by Matt0117** [someaddons/performant_issues#68]
Hello, I have noticed and issue when I try to build up by placing block underneath me blocks are not placed or rarely are. I have removed the mod from my mods folder and deleted the config and this seems to solve the issue. I also have tried turning off all options in the config and still I cannot place blocks. I am using Minecraft 1.12.2, forge 14.23.5.2847, and have many other mods installed. If you wish to inspect my mod folder please contact me. I really enjoy the performance uplift your mod gives so I do hope this gets fixed. Best.

**Comment by someaddons** [comment]
1.12 is very outdated and I don't have the time to update such an old version either, so I suggest you either update to a newer minecraft version or remove the mod

**Comment by Krutoy242** [comment]
Spend 7 hours today to find source of same bug.

Please, add some kind of **"Known Bugs"** or **warning** in mod description about 1.12 version.

This bug was really hard to find, and simple note could save lot of time for other devs.
