### ISSUE TITLE
.26 Seems to speed up crop growth

### ISSUE THREAD

**Issue by crazyirishwrencher** [someaddons/performant_issues#69]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
After updating to performant-1.16.2-4-3.26m.jar (from .25), crop growth speed is greatly increased. Reverted version and normal crop growth speed is observed.

**Comment by LeoBeliik** [comment]
I've noticed this too, and setting **fastChunkBlocks** to false seems to fix the problem.

**Comment by someaddons** [comment]
oh ye good catch, little oversight

**Comment by BugmanBugman** [comment]
Seems to be happening with snow melting too

https://user-images.githubusercontent.com/40730042/103446136-ebf1a700-4c41-11eb-8c6b-3f2a67571340.mp4

**Comment by laserlemons** [comment]
Can confirm. It affects everything that relies on random tick speed.

**Comment by someaddons** [comment]
should be fixed in v3.27m
