### ISSUE TITLE
Performant replaces onServerTick and onWorldTick and will cause issues for mods using those events

### ISSUE THREAD

**Issue by cpw** [someaddons/performant_issues#70]
You are replacing forge's server and world event tick dispatch with something that seems to be trying to amortize those tick costs across time. This is extremely risky for mods that rely on those events firing regularly for things like updating their world state. As such, I would strongly advise removing this. I cannot see any net benefit of doing this. (Trivially, removing a mods' important server or world ticks most of the time will improve performance, but at what cost to the mod in question? Many mods use these events for things like global state updates, and thus those mods missing their events could cause serious data loss for the mods in question).

I have searched the forge issue repository and cannot find any discussion on this amortization. I see no relevant questions on the discord either. I would be fascinated to know why you feel this is an appropriate activity to perform? Do you have numbers supporting this?

I have been thinking about an amortization strategy for potentially costly events like this, however, mods that want to amortize can typically do so very easily with a simple counter (which would probably amplify their incompatibility with this mixin to be honest, since you're now adding double amortization) which is why it's a lower priority than a huge amount of other things.

 I believe this could be a significant performance mod, but it seems you have targeted a core forge functionality with little in the way of community discussion or supporting data for the reasoning (and no apparent thought to the massive sideways impacts to every other mod you are deployed with) and as such this makes this mod a lot less supportable and I have to strongly advocate against it's deployment anywhere whilst this functionality remains.

I've created this ticket because I think discussion on your motivations and understanding your analysis in adding this functionality might be very useful datapoints in trying to improve the core forge ecosystem.

**Comment by someaddons** [comment]
Constant bashing of performance mods in forge disc and now this, I guess your New Year's resolution is to drive more people over to fabric?
![image](https://user-images.githubusercontent.com/38401808/103443996-c629c980-4c64-11eb-8158-9cc75505c675.png)

You've apparently decompiled 10 months old code, who's functionality is even publically documented on curseforge and within the config files. Amazingly you still managed to not actually understand at all what it does nor read the code correctly and even telling people to remove the mod, despite not even beeing able to read the decompiled code, nor the public descriptions.
And people wonder why its closed source or why I don't want to discuss with others all day long...

Maybe you should dedicate your time on getting your own projects straight before bashing on others, if I'm looking at forge I see the mappings in complete shambles, questionable performance at a few places and speaking of Data loss I remember a very recent case where forge royally messed up all worlds dimensions and did not even bother to cleanup after the mess. Should've probably told people to not install forge then?

Lastly I'm not interesting in improving forge in my freetime in the slightest as according to forge disc/ppl I'm too retarted to do so(their choice of word, not mine), I'd rather spend my time on fun stuff.

**Comment by DaemonUmbra** [comment]
> I remember a very recent case where forge royally messed up all worlds dimensions and did not even bother to cleanup after the mess.

I feel like you're talking about the vanilla bug involving the experimental worldgen api available to datapacks, which **isn't Forge's fault**.

**Comment by someaddons** [comment]
I meant this one: https://github.com/MinecraftForge/MinecraftForge/pull/7513
which led to stuff like this: https://github.com/AllTheMods/ATM-6/issues/437 requiring users of existing worlds to edit their level.dat by hand
