### ISSUE TITLE
When First Aid 1.16.4 is installed and using Higher than Forge 35.1.4  no items are dropped on death.

### ISSUE THREAD

**Issue by DaddyP1G** [someaddons/performant_issues#72]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**

I have tested with Forge 35.1.13 and 35.1.28 and happens on both.  If you have First Aid Installed, when you die, no items drop and your inventory disappears.   If you install a Tomb mod like CoRail, nothing shows up either. 

**To Reproduce**
1. Install First Aid for 1.16.4 and Performant
2. Go in game and get equipment
3. DIE
4.  REPEAT

**Expected behavior**
Items or Tomb to spawn

**Screenshots**

** Mod version **
Your mods version

** Logs **
Latest/Crash log

There is nothing posted to LOGS.  Not even a death notice.

**Comment by ravenbuilder934** [comment]
We have performant and Corail's on the minecolonies patreon server and graves work fine

**Comment by DaddyP1G** [comment]
It happens when First Aid is installed

**Comment by ravenbuilder934** [comment]
> If you install a Tomb mod like CoRail, nothing shows up either.

**Comment by someaddons** [comment]
should be fixed in v3.27m
