### ISSUE TITLE
Bees suffocating

### ISSUE THREAD

**Issue by Maltshakes** [someaddons/performant_issues#74]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
My bees suffocate when trying to pollinate trees from the Fruit Trees mod. To pollinate, they must enter the leaf block. With Performant installed, they begin to suffocate. This is on Forge 35.1.13, Performant version 1.16.2-4-3.25. Is there something I need to change in the Performant config to fix this?

**To Reproduce**
1. Install forge mods Performant and Fruit Trees
2. Load a new world
3. Teleport to plains biome and locate fruit trees, place bees
4. Observe bees try to enter blooming leaf blocks and take suffocation damage

**Expected behavior**
Without Performant installed, the bees enter the blooming leaf blocks from the Fruit Trees mod and collect pollen without suffocation. This is necessary in order to cross breed fruit trees. 

** Mod version **
Performant version 1.16.2-4-3.25. 
[Fruit Trees Mod](https://www.curseforge.com/minecraft/mc-mods/fruit-trees)

**Comment by BugmanBugman** [comment]
Try updating your version, and try the passable foliage mod

**Comment by Maltshakes** [comment]
I've just tried the updated version and there is no change, bees still suffocate. 

The passable foliage mod does seem to correct the bee suffocating issue, but now brings the issue that all entities can walk through leaves. The config does not allow you to set which entities are permitted. So while it's fixed one issue it's caused another.

**Comment by someaddons** [comment]
should be fixed in v3.27m
