### ISSUE TITLE
how do i modify the config on 1.16 servers?

### ISSUE THREAD

**Issue by Poke5555** [someaddons/performant_issues#75]
there isnt a config file inside the world folder and modifying the one in the config folder doesnt change anything.
sorry if this has a simple answer, i just cant figure it out.

**Comment by BugmanBugman** [comment]
It’s in the config folder but you may need to restart your game

**Comment by Poke5555** [comment]
yea turns out that does work, it just doesnt effect my enderman farm. the overworld however..... ive never seen so many mobs.

**Comment by Poke5555** [comment]
https://i.imgur.com/x6RqGPW.png
