### ISSUE TITLE
incompatibility with Corpse

### ISSUE THREAD

**Issue by TsplayerT** [someaddons/performant_issues#77]
In a simple way, the title describes what happened 🤷‍♂️

I noticed that corpses created without the Performant mod being loaded are fine, but when it is loaded and dies it does not generate the body.

[latest.log](https://github.com/henkelmax/corpse/files/5756484/latest.log)
[debug.log](https://github.com/henkelmax/corpse/files/5756485/debug.log)

**Versions**
- Minecraft version: 1.16.4
- Forge version: 35.1.13
- Corpse Mod version: 1.16.4-1.0.4

**Comment by someaddons** [comment]
should be fixed in v3.27m
