### ISSUE TITLE
Weird issue with teleporting to dimension 

### ISSUE THREAD

**Issue by Sunekaer** [someaddons/performant_issues#78]
https://s1.sunekaer.com/files/04-01-2021_19-30-05_%25pn.mp4

**To Reproduce**
Rat + Ratlantis + Performant 
Create world 
get one rats:chunky_cheese_token from creative
Click it on the ground, wait for portal to spawn
Go through portal and watch the loop until you crash from running out of memory

**Expected behavior**
to not be in a loop of getting tp´ed between dims

**Screenshots**

**Mod version**  (Full mod list https://paste.sunekaer.com/uxojifatiq.css )
rats-7.0.3-1.16.3.jar
ratlantis-1.0.0-1.16.3.jar
performant-1.16.2-4-3.25m.jar and performant-1.16.2-4-3.26m.jar

No errors in log

**Comment by someaddons** [comment]
should be fixed in v3.27m
