### ISSUE TITLE
Crash with AE

### ISSUE THREAD

**Issue by Sunekaer** [someaddons/performant_issues#79]
from issue https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/80
* **Issue**: There is a bug I think with applied energistics that has caused an infinite loop, causing my multiplayer server to crash constantly. I tried to autocraft molecular assemblers I think for the first time and the server crashed and wouldn't restart. Only thing I could do was load a backup. There were 3 people on at the time, but I'm pretty sure this is the cause since it crashed as soon as I confirmed the autocraft.

* **Link to Log or Crash File Paste**: https://pastebin.com/gLAZBQFd

We didn't see this issue before adding performant

**Comment by someaddons** [comment]
Unlikely to be performant as all it does is forward/take the time of the execution, not modify it. If its reproduceable try removing performant and test
