### ISSUE TITLE
[1.16.1] crash on server load

### ISSUE THREAD

**Issue by jinkhya** [someaddons/performant_issues#8]
**Describe the bug**
Crash on server load

**To Reproduce**
We're currently running Enigmatica 6 modpack, and adding performant mod to it prevents the server to load. I'll give you the log.
If you want me to do further testing let me know :)

**Expected behavior**
The server not to crash.

** Mod version **
performant-1.16-3.10m

** Logs **
https://gist.github.com/jinkhya/b451f887df6fe9be8aeb5cdd63dbcf1b

**Comment by someaddons** [comment]
oh thats def not intended :) seems to be the first mod conflict

**Comment by someaddons** [comment]
should be fixed in 3.11m

**Comment by jinkhya** [comment]
lemme test :)

**Comment by jinkhya** [comment]
derp, you have posted it yet. I'll test whenever it's available ! ^^

**Comment by jinkhya** [comment]
It loaded perfectly fine ! thank you !

**Comment by someaddons** [comment]
nice :) and interesting that you didnt see the post right away, posted on patreon before here
