### ISSUE TITLE
With Dyanmic Surroundings and Performant, Dynamic surroundings noises such as the weapon swinging don't work

### ISSUE THREAD

**Issue by BugmanBugman** [someaddons/performant_issues#80]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
title

**To Reproduce**
1. take out a weapon
2. notice how it doesnt make a sound
3. test the game without performant 
4. notice how it does

**Expected behavior**
For weapons to make sounds

** Mod version **
3.26
https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings

**Comment by someaddons** [comment]
might be fixed with version 3.27m at least I can't reproduce it

**Comment by BugmanBugman** [comment]
I figured it out, it only seems to happen in conjunction with the ModernUI mod
https://www.curseforge.com/minecraft/mc-mods/modern-ui

**Comment by someaddons** [comment]
Fixed in performant 3.30m
