### ISSUE TITLE
random Ticks stop Appear to stop, after loading.

### ISSUE THREAD

**Issue by Kutora** [someaddons/performant_issues#84]
**Describe the bug.**
### Random Ticks stop happening after less than a minute of loading into the world.
(evidenced by farmlands' hydration, Redstone ore's glow & particle, Grass regrowth & death and crops' lack of change.)
**To Reproduce**
1. Start world
2. Wait (took less than 15 seconds for me)
2.5(Optional): change gamerule randomTickSpeed to your heart's desire !
    (helpful for verifying that your RNG isn't just astronomically bad)
3. observe Redstone ore, farmland, Grass/Dirt, and crops to heart's content.
    They won't change! (Unless  acted on externally I.E.: bone meal, or interacting with the Redstone ore, if it hasn't been activated)

**Expected behavior**
Random ticks should save these poor blocks, from their newly found, performant ale'd, sad eternal damnation 

**Screenshots**
You bet!
![2021-01-07_00 42 48](https://user-images.githubusercontent.com/32602050/103857163-cb26b880-506a-11eb-8f18-39b8ae6ffaf7.png)

** Mod version **
1.16.2 ver. 4-3.28m

** Logs **
[latest (14).log](https://github.com/someaddons/performant_issues/files/5779843/latest.14.log)

**Comment by rigerc** [comment]
Also came across this bug today, setting fastChunkBlocks  to false seems to have fixed it

**Comment by tharrmeehan** [comment]
> Also came across this bug today, setting fastChunkBlocks to false seems to have fixed it

Came across this too, setting this option to false worked partially for me. 
Some crops like sugar cane were still not able to grow for me.

**Comment by Gbergz** [comment]
Can confirm, Random Ticks doesn't appear to work when I add performant to a clean instance.

**Comment by missionz3r0** [comment]
Just throwing my hat with the others to say I am experiencing the same issue. Seems to be the inverse of #69

**Comment by someaddons** [comment]
fixed in 3.29
