### ISSUE TITLE
 Performant mod is very likely to produce fatal errors, please consider this closely

### ISSUE THREAD

**Issue by simplebunsen** [someaddons/performant_issues#85]
When starting minecraft with a fairly basic modding configuration, the following warning occurs during loading and is shown before the main menu.

Performant mod is very likely to produce fatal errors, please consider this closely

latest.log: https://pastebin.com/u7QaiWKR

** Mod version **
Your mods version: 3.29m

using forge 35.1.36

**Comment by someaddons** [comment]
ignore it apparently the ModernUI dev added it

**Comment by BloCamLimb** [comment]
I guess Performant somehow breaks ServerChunkProvider or Forge EventBus.
