### ISSUE TITLE
Server crash possibly due to CustomGoalSelector

### ISSUE THREAD

**Issue by Awfullyfishy** [someaddons/performant_issues#87]
Not entirely sure what happened, but at some point a MP server crashed and was unable to boot back up. Logs mention performant.coremod.entity.ai.CustomGoalSelector and skeleton horses.
Also mentions the Eidolon mod, but I find it more likely Performant caused it, but you can tell me I'm wrong since I'm not entirely sure.

Error from server logs
https://pastebin.com/wUXSSRy2

First crash log
https://pastebin.com/NVm2TGvu

Second crash log
https://pastebin.com/nrQPBgn0

**Comment by someaddons** [comment]
ah these are hard to trackdown, something is removing an AI task incorrectly during the AI task list updating, but the crash only happens afterwards. So the actual problem happens right before and probably is not visible

**Comment by Awfullyfishy** [comment]
Will hope it doesn't come up again in that case. Is there any way to track it down somehow?

**Comment by zEpiixz** [comment]
i have the same problem with the latest and the downgraded version
https://pastebin.com/huKnTYdH

**Comment by malte0811** [comment]
This should be fixed in Forge build 35.1.34 (or at least one crash of the type @someaddons mentioned related to skeleton horses).

**Comment by someaddons** [comment]
nice to know, thx :D

**Comment by KKotik** [comment]
Having same issue that make my server lag. 
https://spark.lucko.me/#pWszj3qzxj

**Comment by SpycrabSXL** [comment]
I also have a multiplayer server crashing due to this issue, however this time it seems to be a skeleton that has became a named mob due to apotheosis.

https://pastebin.com/FqUdWQ15

**Comment by someaddons** [comment]
should be fixed in 3.40m
