### ISSUE TITLE
Performant causes crashes 

### ISSUE THREAD

**Issue by DamienBrittan** [someaddons/performant_issues#88]
When having it in my mod folder it causes crash at the start of loading mojang logo .
latest log - https://gist.github.com/DamienBrittan/16cc5f53152ef52b8607a0c0c8a8aa7e
performant-1.16.2-4-3.30m.jar

**Comment by someaddons** [comment]
crashlog? mods used?

**Comment by DamienBrittan** [comment]
there was no crashlog for somereason . i've used more than 100 mods

**Comment by someaddons** [comment]
random patches installed? if so which version

**Comment by DamienBrittan** [comment]
randompatches-1.16.4-1.22.1.11

**Comment by DamienBrittan** [comment]
updated randompatches to the last version 
seems to be fine so far . thanks
