### ISSUE TITLE
Inventory RefinedStorage blocks lighting issue when betterFPS option in config is enabled

### ISSUE THREAD

**Issue by Caffeinew** [someaddons/performant_issues#93]
When using default config / betterFPS = true, some of RefinedStorage blocks have incorrect lighting on the top side, but only while rendered in inventory / JEI. I'd assume the issue is on refined's side, since they're using forge's experemental lighting pipeline, but i'll report it here, just in case.
![smth](https://user-images.githubusercontent.com/61048648/105218648-7d2fab80-5b66-11eb-96dc-b9aa7602da9a.png)

**Comment by Tander** [comment]
The same issue with Environmental Tech (for example, "envirocore:fe_input" block). Probably it's because of multi-layered textures on such blocks

**Comment by someaddons** [comment]
fixed
