### ISSUE TITLE
Server crash, unsure why.

### ISSUE THREAD

**Issue by DevyHeavy** [someaddons/performant_issues#94]
Hi, my forge 1.15.2 server crashes often. Below is the server crash report. I am using version 3.16m.

https://pastebin.com/1DwapPXV

**Comment by ravenbuilder934** [comment]
> cam72cam

Do you know which mod this is? If you do, try removing it and running the server again

**Comment by DevyHeavy** [comment]
Looks to be Immersive railroading.

I will remove it next time the server crashes (it almost seems to be random when it crashes).

**Comment by someaddons** [comment]
should be fixed in 3.40m
