### ISSUE TITLE
Conflict with Astral Sorcery - Aevitas Mantle of Stars sky-walking ability

### ISSUE THREAD

**Issue by Mooncat25** [someaddons/performant_issues#95]
**Description**
This mod somehow disabled the sky-walking ability of the Aevitas Mantle of Stars (armor) in the Astral Sorcery mod.

First noticed this in the Valhelsia 3 mod pack with the following mod versions in concern:
Astral Sorcery - 1.16.4-1.13.8
ObserverLib - 1.16.4-1.4.4 (required by AS)
Curios API (Forge) - 1.16.4-4.0.3.0 (required by AS)
Performant - 1.16.2-4-3.25m

However, updating them to the latest versions (stated as below) won't help fixing the problem.

**To Reproduce**
1. Install Minecraft 1.16.4, Forge, [Astral Sorcery](https://www.curseforge.com/minecraft/mc-mods/astral-sorcery), [ObserverLib](https://www.curseforge.com/minecraft/mc-mods/observerlib) and [Curios API (Forge)](https://www.curseforge.com/minecraft/mc-mods/curios)
2. Launch Minecraft and create a Creative world.
3. AS seems to disallow sky-walking if you don't have the appropriate progress (maybe anti-cheat?). Fortunately, AS provides the command to maximize your progress immediately. Type `/astralsorcery maximize` and press enter. The AS advancements should be unlocked after this.
4. Search item "Aevitas" and the Mantle of Stars armor should appear. Take it. Equip it.
5. Go to any block that is higher than the others. Make sure you are not in creative flying mode. Try to walk off the block. If you don't fall, the armor is walking.
6. Now also install `Performant` and restart step 2 - 5.

**Expected behavior**
The Aevitas Mantle of Stars should grant you sky-walking ability. Thus, you shouldn't fall in step 5.

**Mod version**
Astral Sorcery - 1.16.4-1.13.9
ObserverLib - 1.16.4-1.5.1
Curios API (Forge) - 1.16.4-4.0.3.4
Performant - 1.16.2-4-3.30m

**Logs**
[latest.log](https://gist.github.com/exsnowcat/b254cb6a2c1eea3e7cead3683348b36e)

**Comment by StarwaII** [comment]
I can confirm this bug, but I was able to fix it by setting fastCollisions to false in the performant-common.toml config file. Hope this helps!

**Comment by exsnowcat** [comment]
> I can confirm this bug, but I was able to fix it by setting fastCollisions to false in the performant-common.toml config file. Hope this helps!

Yes, this fixes the issue! But I think it also disables the `multiEntities`? Hope we'll have a proper fix later.

**Comment by Mooncat25** [comment]
Hi, I'm back and I'm happy to say this bug seems to be resolved in the newest version of Performant, with `fastCollisions = true`.
The Aevitas Mantle can have sky-walking ability without problem in the following environment:

- Minecraft 1.16.5
- Forge 36.1.0
- Performant 1.16.2-5-3.40m
- Astral Sorcery 1.16.4-1.13.9
- ObserverLib - 1.16.4-1.5.1 (required by AS)
- Curios API (Forge) - 1.16.5-4.0.5.0 (required by AS)

Hence, I'm closing this issue. Thank you for the update.
