### ISSUE TITLE
Performant and Rats gives error in console

### ISSUE THREAD

**Issue by TheCoolestPaul** [someaddons/performant_issues#96]
**Describe the bug. 1.12 is no longer supported, do not make bug reports for it.**
Sometimes this error will be the last thing in console before a crash and sometimes the server will continue running and this error will pop into console a few times in a matter of minutes.

**To Reproduce**
1. Start a server with BOTH Performant and Rats mods installed.
2. Give it a few minutes
3. This error will be put into console
?. The server will crash or the server will stutter for a few seconds and continue as normal.

**Expected behavior**
No errors in console.

**Screenshots**

**Versions**
Performant 3.30m
Rats 7.1.0

**Logs**
Latest/Crash log
[the error](https://pastebin.com/epzKysCu)

**Comment by MimiVRC** [comment]
we have the same issue with performant and Rats

**Comment by TheCoolestPaul** [comment]
I have also opened an issue with Rats as you can see above.

**Comment by Boymann** [comment]
I have also experienced this.

**Comment by someaddons** [comment]
should be fixed
