### ISSUE TITLE
Error crashing in the End

### ISSUE THREAD

**Issue by Firehead94** [someaddons/performant_issues#97]
The error occurs when loading the outer ring in the End while playing Valhalsia 3 v3.1.6 modpack. the server hangs until it finally crashes. Removing Performant fixes the issue.

**To Reproduce**
1. Go to the outer ring of The End and fly around for awhile. Happened to me near end cities almost all the time.
2. See error

**Expected behavior**
The server not to crash

** Mod version **
Valhelsia3 3.1.6
Minecraft Version 1.16.5

** Logs **
Debug: https://pastebin.com/ecE1Fyj7
Crash: https://pastebin.com/333Q0nAC
Latest: https://pastebin.com/YygEU7zt

**Comment by darkcamo12** [comment]
With my testing of the mod pack AllTheMods 6 which has performant in it I found turning "fixBlockBreakGoal =" to false seems to have fixed the end crash

I had only done this a few days ago so it's still early

**Comment by someaddons** [comment]
should be fixed in 3.40m
