### ISSUE TITLE
Performant with Camera Overhaul causes screen to jitter while idle

### ISSUE THREAD

**Issue by BugmanBugman** [someaddons/performant_issues#98]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
title. the screen slowly jitters while you're in place. it doesn't happen without performant.

**To Reproduce**
1. start up minecraft with performant and camera overhaul
2. join a world
3. notice how the screen jitters while you stand still

**Expected behavior**
for it to not jitter 

** Mod version **
Your mods version
3.30m
https://www.curseforge.com/minecraft/mc-mods/camera-overhaul-forge

**Comment by RHSD** [comment]
Can confirm the bug is present in 1.16.5 with latest versions of forge, camera overhaul and performant.

**Comment by Reddy64** [comment]
Temporary solution until this is addressed:

![image](https://user-images.githubusercontent.com/80792439/111384815-5088a380-8680-11eb-8204-848d873e9c3f.png)

Just set fastCollisions to false, it should do the trick.

**Comment by someaddons** [comment]
should be fixed in 3.40m
